aws/amazon-chime-sdk-component-library-react

- .github/workflows/publish.yml
- CHANGELOG.md
**Issue #:** 
- Re-enables the publishing workflow, making sure to build the component library before publishing it
**Testing**
> Re-enable github action publishing workflow

- CHANGELOG.md
- README.md
**Issue #:** 
Add npm package and CI build flow badge to package README
<a href="https://www.npmjs.com/package/amazon-chime-sdk-component-library-react"><img src="https://img.shields.io/npm/v/amazon-chime-sdk-component-library-react?style=flat-square"></a>
<a href="https://github.com/aws/amazon-chime-sdk-component-library-react"><img src="https://github.com/aws/amazon-chime-sdk-component-library-react/workflows/CI%20Workflow/badge.svg"></a>
**Testing**
1. Have you successfully run `npm run build:release` locally? no
> Add npm & build badges

- CHANGELOG.md
- scripts/check-codestyle.js
Fix ```npm run build:release``` script execution on Windows OS.
**Testing** 
Running build on windows 10
> Fix build:release run on windows OS

- CHANGELOG.md
- demo/meeting/package-lock.json
- package-lock.json
- package.json
- src/components/introduction.stories.mdx
- src/components/sdk/introduction.stories.mdx
- Update Storybook to 5.3
- Adjust docs after moving styled system and sdk to peer dependencies
This doesn't fix the dependency vulnerability issue unfortunately, but I've submitted a report to npm for Storybook
**Testing**
manually building storybook
> Update Storybook to 5.3

- CHANGELOG.md
- src/components/sdk/MeetingControls/AudioInputControl.tsx
**Issue #:** 
- Fixed reversed labels for mute/unmute control in `AudioInputControl`
**Testing**
2. How did you test these changes? Locally running the demo app
> Correct reversed labels for mute/unmute control

- demo/meeting/README.MD
- demo/meeting/package-lock.json
- demo/meeting/package.json
**Issue #: NA** 
Improvements to demo meeting dev server
1. Run both webpack server and node server on the same terminal
* Developers have to open two terminals and run two different commands in order to test the demo site
* Modified configuration which now requires only running one command `npm run start` to run the demo site.
**Testing**
Yes
Yes. Follow there steps to test:
1. Clone repo
2. run `cd demo/meeting`
3. run `npm i`
4. run `npm run start`
5. In browser open `localhost:9000`
6. You should be able to connect to a meeting. (AWS credentials setup required)
3. If you made changes to the component library, have you provided corresponding documentation …
> Demo meeting dev server improvements

- package-lock.json
**Issue #:** 
Bump package dependencies version by running npm audit fix after removing all build artifacts to resolve some security vulnerabilities - https://github.com/aws/amazon-chime-sdk-component-library-react/security. 
**Testing**
Yes
n/a
n/a
> Upgrade dependencies version to resolve some security vulnerabilities

- CHANGELOG.md
- src/components/sdk/PreviewVideo/index.tsx
**Issue #:** 
- When selecting a new video input device, the preview won't re-render, and the unmounting behavior causes us to lose the media stream
- Re-render when a new device is selected
- Reselect video input device to make sure we have a video strema
**Testing**
n/a
> Fix PreviewVideo component when selecting new video input

- scripts/verdaccio.js
**Issue #:** 
Update verdaccio script to use npm run start, instead of run start:client. That way, we don't have to explicitly create another tab to run the backend server
**Testing**
yes
ran 'node scripts/verdaccio.js' locally and verified it ran the server with the demo app 
n/a
> Modify verdaccio script to use npm run start

- demo/meeting/src/containers/MeetingForm/index.tsx
if Demo meting URL has `meetingId` part of query params we can parse and insert in to the join meeting form.
https://0.0.0.0:9000/?meetingId=metting123
**Testing**
> Add ability  meetingId from query params

- CHANGELOG.md
- src/components/ui/Base/index.ts
**Issue #:** 
Styled Components adjusts the order of style declarations when it comes to media queries, so the `css` prop was not taking precedence over previously declared styles
[Ticket with more details here](https://github.com/styled-components/styled-components/issues/2095)
- Wrap the `css` prop in a blank media query so it retains its order
**Testing**
> Fix css prop not taking precedence over queries

- CHANGELOG.md
- demo/meeting/src/containers/MeetingMetrics/Styled.ts
- demo/meeting/src/containers/MeetingMetrics/index.tsx
- demo/meeting/src/containers/Navigation/index.tsx
- demo/meeting/src/providers/NavigationProvider.tsx
- demo/meeting/src/views/Meeting/index.tsx
- src/hooks/sdk/docs/useBandwidthMetrics.stories.mdx
- src/hooks/sdk/useBandwidthMetrics.tsx
- src/index.ts
Displays incoming/outgoing bandwidth usage for an active meeting session
**Testing**
yes
> Add bandwidth metrics to demo

- CHANGELOG.md
- src/providers/RosterProvider/docs/RosterProvider.stories.mdx
- src/providers/UserActivityProvider/docs/UserActivityProvider.stories.mdx
- src/providers/UserActivityProvider/docs/useUserActivityState.stories.mdx
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/172
Add documentation for UserActivityProvider and RosterProvider
**Testing**
yes
> Add documentation for UserActivityProvider and RosterProvider

- CHANGELOG.md
- src/components/sdk/DeviceSelection/CameraSelection/index.tsx
- src/components/sdk/DeviceSelection/DeviceInput.tsx
- src/components/sdk/DeviceSelection/MicSelection/index.tsx
- src/components/sdk/DeviceSelection/SpeakerSelection/index.tsx
- src/components/sdk/DeviceSelection/docs/CameraSelection.stories.mdx
- src/components/sdk/DeviceSelection/docs/MicSelection.stories.mdx
- src/components/sdk/DeviceSelection/docs/SpeakerSelection.stories.mdx
- src/providers/DevicesProvider/AudioOutputProvider.tsx
**Issue #:** 
Use hooks instead of a local state inside Device Input
**Testing**
- Selected difference devices in the /devices page (preview page) and verified that the correct selected devices showed up
yes
> Update device selectors to use hooks instead of local state

- CHANGELOG.md
- src/hooks/sdk/useAttendeeStatus.tsx
**Issue #:** 
When disabling your local video, there is still a video tile present in the session. This was causing incorrect state for the local user when using `useAttendeeStatus` on mount.
Fixes above bug by checking if the tile is active
**Testing**
yes
n/a
> Fix useAttendeeStatus local user bug

- CHANGELOG.md
- src/hooks/sdk/useToggleLocalMute.tsx
**Issue #:** #190 
useToggleLocalMute not working when audioVideo initialized after component
Fixes the bug above by re-initializing state & updating callback when audioVideo changes
**Testing**
Yes.
Using our local chime application as well as a regression with demo/meeting
Yes.
> useToggleLocalMute: Initialize muted when audioVideo changed

- CHANGELOG.md
- src/hooks/sdk/docs/useLocalAudioInputActivity.stories.mdx
- src/hooks/sdk/useLocalAudioInputActivity.tsx
- src/hooks/sdk/useLocalAudioInputActivityPreview.tsx
- src/index.ts
**Issue #:** 
- [Issue](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/183) 
- [Issue](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/182)
- Adds audioVideo to dep list for `useLocalAudioInputActivityPreview`
- Takes additional cb param for custom logic
**Testing**
yes
> Add av dep and additional cb to useLocalAudioInputActivityPreview

- CHANGELOG.md
- src/components/ui/Input/Styled.tsx
> Fix search icon alignment

- CHANGELOG.md
- src/components/ui/Roster/RosterCell/Styled.tsx
**Issue #:** 
Depending upon the styles applied higher up in the tree, the `Mic` icon can inherit a `line-height` that pushes the icon our of alignment. This change will prevent that.
**Testing**
eyeballing the change in Storybook
This change doesn't require documentation.
> Ensure vertical alignment for roster cell icons

- CHANGELOG.md
- demo/meeting/package-lock.json
- demo/meeting/package.json
**Issue #:** 
[dependabot alert](https://github.com/aws/amazon-chime-sdk-component-library-react/network/alert/demo/meeting/package-lock.json/node-forge/open)
Upgraded `webpack-dev-server` to fix `node-forge` security vulnerability alert
**Testing**
Yes
Ran demo app locally to check if any breaking changes, found none.
NA
> Upgrade webpack-dev-server to fix node-forge security vulnerability alert

- CHANGELOG.md
- src/components/ui/ControlBar/ControlBarItem.tsx
- src/components/ui/ControlBar/Styled.tsx
- src/components/ui/PopOver/index.tsx
- src/theme/dark.ts
- src/theme/light.ts
- src/theme/styled.d.ts
Currently there's not way to manipulate a `button` in the `ControlBar` to give visual feedback that it is active, or toggled. This can be useful to give more visual feedback for states such as when a users' camera is on. This change introduces an optional `isActive` prop for a `ControlBarButton` component.
**Testing**
I am experiencing issues with running snapshot tests. Other than that release ran without issue.
Manually, (and hopefully with an updated snapshot test when I can get them to work).
Yes
By submitting this pull request, I confirm that my contribution …
> Include prop for ControlBarButton active state

- src/components/ui/Roster/RosterHeader.tsx
- tst/components/ui/Roster/RosterHeader.test.tsx
**Issue #:** 
When the RosterHeader component was in Search mode, there was no event data passed out of it when a user clicked the native "clear Search" (Note: capitalization mistake) "X" icon in the search element to signify that the search is done.
**Testing**
2. How did you test these changes? `npm run test` new tests
> Added onSearch callback for when a search is cleared

- CHANGELOG.md
- src/components/ui/Select/index.tsx
**Issue #:** 
demo build fails due to unused import
remove import
**Testing**
2. How did you test these changes? started demo after removing node_modules directories
> Remove unused import in Select

- CHANGELOG.md
- src/components/sdk/VideoTileGrid/index.tsx
- src/components/ui/VideoGrid/index.tsx
**Issue #:** 
Fixes issue #211 
Allow layout prop to VideoTileGrid for developers who want to choose between a featured video layout and a standard video layout 
**Testing**
> Add layout prop for VideoTileGrid

- CHANGELOG.md
- demo/meeting/src/containers/EndMeetingControl/index.tsx
- demo/meeting/src/containers/MeetingControls/index.tsx
- src/components/sdk/MeetingControls/AudioInputControl.tsx
- src/components/sdk/MeetingControls/AudioOutputControl.tsx
- src/components/sdk/MeetingControls/ContentShareControl.tsx
- src/components/sdk/MeetingControls/VideoInputControl.tsx
- src/components/sdk/MeetingControls/docs/AudioInputControl.stories.mdx
- src/components/sdk/MeetingControls/docs/AudioOutputControl.stories.mdx
- src/components/sdk/MeetingControls/docs/ContentShareControl.stories.mdx
- src/components/sdk/MeetingControls/docs/VideoInputControl.stories.mdx
- src/components/ui/ControlBar/ControlBarItem.tsx
- src/components/ui/Navbar/NavbarItem.tsx
- src/index.ts
- tst/components/ui/ControlBar/ControlBarItem.test.tsx
**Issue #216:** 
The component was renamed from `ControlBarButton` to` ControlBarItem` and the export name `ControlBarItem`.
Before this change, the component was exported as `ControlBarButton`
**Testing**
yes
By running the `storybook` in Chrome/FireFox/Safari
yes
> Fix rename component ControlBarButton to ControlBarItem

- CHANGELOG.md
- src/providers/RosterProvider/docs/RosterProvider.stories.mdx
- src/providers/RosterProvider/docs/useRosterState.stories.mdx
rename variable `rosterArray ` from the attendees list to `attendees`
```diff
-  const rosterArray = Object.values(roster);
+  const attendees = Object.values(roster);
const attendeeItems = attendees.map(attendee => 
```
```diff
-  const rosterArray = Object.values(roster);
+  const attendees = Object.values(roster);
const attendeeItems = attendees.map(attendee => 
```
**Testing**
yes
By running the `storybook`
No
> Docs rename variable from the attendees list

- CHANGELOG.md
- src/components/sdk/Base/index.tsx
- src/components/ui/Base/index.ts
**Issue #:** 
Adds tabIndex to base props, also just extending the base SDK props since they just overlap for now
**Testing**
2. How did you test these changes? adding tabIndex props to demo and checking for build errors
3. If you made changes to the component library, have you provided corresponding documentation changes? yeah
> Add tabIndex to base props

- CHANGELOG.md
- src/components/ui/Chat/ChatBubble/createChatBubbleList.tsx
- src/components/ui/Chat/InfiniteList/Styled.tsx
- src/components/ui/Chat/InfiniteList/index.tsx
- src/index.ts
- tst/components/ui/Chat/ChatBubble/createChatBubbleList.test.tsx
This commit adds new message scrolling behavior to the `<InfiniteList/>` component. If the user is at the bottom of the list and a new message appears, the list will automatically scroll down to view the new message. But if the user is not at the bottom of the list, it will not scroll, so the user can continue to read other messages. 
Additionally, this commit slightly changes the data type `Message` and correctly exports these chat components. There was also some test clean up. 
**Testing**
Yes
Tested in the demo app and storybook. 
n/a
By submitting this pull …
> Add chat message component enhancements

- CHANGELOG.md
- src/components/ui/Roster/Roster.mdx
- src/components/ui/Roster/Roster.stories.tsx
- src/components/ui/Roster/RosterHeader.tsx
- tst/components/ui/Roster/RosterHeader.test.tsx
**Issue #:** 
n/a
The range of controls in the `RosterHeader` are very useful, but a little rigid. Allowing the rendering of children will provide some flexibility. I thought it would be helpful to incorporate it alongside the existing options, rather than make it a 'children or all of these optional props' kind of deal
**Testing**
yes
unit tests, and manual test in storybook
yes
> use children prop in RosterHeader for custom elements

- CHANGELOG.md
- src/components/ui/Chat/DateHeader/index.tsx
Adds a className to the `<DateHeader>` component for easier access to styling, especially when using the `insertDateHeaders` helper function and the user doesn't access the `<DateHeader>` component directly. 
**Testing**
Yes
Used the components in a demo
n/a
> Add class to DateHeader component for easier styling access.

- CHANGELOG.md
- src/components/ui/Roster/PopOverMenu.tsx
- src/components/ui/Roster/RosterCell/index.tsx
Added buttonProps passthrough for RosterCell and PopOverMenu
**Testing**
2. How did you test these changes? tested in another code base
> Added buttonProps passthrough for RosterCell and PopOverMenu

- CHANGELOG.md
- src/components/ui/Chat/InfiniteList/InfiniteList.mdx
- src/components/ui/Modal/Modal.stories.tsx
- src/components/ui/Modal/ModalBody.tsx
- src/components/ui/Modal/ModalHeader.tsx
- src/components/ui/Modal/index.tsx
Change prop tree to allow modal components to receive custom classNames.
Also fixed one old line in InfiniteScrollingList documentation.
**Testing**
yes
storybook
n/a
> Allow modal components to receive css classNames

- CHANGELOG.md
- package-lock.json
- package.json
- src/providers/MeetingProvider/MeetingManager.ts
**Description of changes:** 
bump chime-js-sdk version to 1.22 
updated demo application to work with chime-js-sdk v1 & v2
**Testing**
2. How did you test these changes? by manualy installing v1 and v2 and test app with both versions.
> Bump chime-js-sdk version

- CHANGELOG.md
- src/components/ui/Chat/InfiniteList/InfiniteList.stories.tsx
- src/components/ui/Chat/InfiniteList/index.tsx
**Issue #:** 
The intersection observers need to be defined outside of the useEffect hook. Also providing root to the intersection observers seems to not add value.
**Testing**
Yes
Storybook
n/a
> Fix a bug that made this list not reusable

- CHANGELOG.md
- demo/meeting/src/containers/EndMeetingControl/index.tsx
- demo/meeting/src/utils/TestSound.tsx
- src/providers/MeetingProvider/MeetingManager.ts
V2 readiness at this point components works with v1 and v2 of chime-sdk-js
**Testing**
tested with v1 and v2 QA approved!
> Readiness for chime-js-sdk v2 support

- CHANGELOG.md
- src/components/ui/icons/HandRaise/Styled.tsx
- src/providers/RosterProvider/docs/RosterProvider.stories.mdx
- src/providers/RosterProvider/index.tsx
**Issue #:** 
issue #278 
Allow developers to pass additional data to RosterProvider if needed
**Testing**
Added a random property in the demo's getAttendee function, verified video tiles and roster worked as intended
yes
> Allow arbitrary to be passed to RosterProvider

- src/components/ui/Checkbox/index.tsx
- src/components/ui/icons/HandRaise/Styled.tsx
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/247
fix a bug related to showing the wrong layout for checkbox labels when used in a formfield. This fix will show the label correctly, after the checkbox.
**Testing**
locally created a formfield and added the checkbox as the layout type and verified the layout. 
n/a
> Fix layout bug with Checkbox in Formfield

- CHANGELOG.md
- src/components/ui/PopOver/Styled.tsx
**Issue #:** 
306
Fix issue 306. Caused by a recent change to popover styles.
**Testing**
Yes
Storybook
n/a
> Fix popover submenu being hidden

- CHANGELOG.md
- demo/meeting/src/utils/TestSound.tsx
**Issue #:** 
Demo test speaker functionality was broken
Fixes small typo. Should eventually split this test speaker code into a separate method instead of having the async code in the constructor
**Testing**
2. How did you test these changes? manually in chrome, ff, safari on Mac
> Fix demo test speaker

- CHANGELOG.md
- src/components/ui/Select/Styled.tsx
**Issue #:** 
The arrow icons on the `Select` component blocks clicks, blocking a chunk of the interaction area. Adding some CSS to let clicks pass through the icons
**Testing**
2. How did you test these changes? manually in chrome by clicking on select arrows to open the dropdown
> Fix select component click through

- CHANGELOG.md
- src/components/sdk/DeviceSelection/MicSelection/index.tsx
- src/components/sdk/DeviceSelection/SpeakerSelection/index.tsx
- src/hooks/sdk/docs/useSelectAudioInputDevice.stories.mdx
- src/hooks/sdk/docs/useSelectAudioOutputDevice.stories.mdx
- src/hooks/sdk/docs/useSelectVideoInputDevice.stories.mdx
- src/hooks/sdk/useSelectAudioInputDevice.tsx
- src/hooks/sdk/useSelectAudioOutputDevice.tsx
- src/index.ts
**Issue #:** 
#321
Exposes hooks for selecting audio input/output. For some reason we exposed hooks for video selection, but not audio.
**Testing**
2. How did you test these changes? manually in chrome, ff
> Hooks for selecting audio input and ouput

- CHANGELOG.md
- src/components/ui/Base/index.ts
**Issue #:** 
N/A
Small change to `baseProps` for UI components so that they can receive an 'id' prop. This can be useful when applying `aria-describedby` attributes. 
**Testing**
2. yes
2. How did you test these changes?   
Manually and by running unit tests
The baseProps do not currently have documentation
> allow an optional id prop to all components

- CHANGELOG.md
- package.json
Removing "-s public" flag from the build-storybook script which attempts to load static files from the public folder. This flag is not needed and causes the build to fail when run in Github Actions.
**Testing**
Yes
Submitted a test workflow to run build-storybook in a Github Actions flow. This script is normally only run on release.
> Fix build-storybook error in Github Actions

- demo/chat/package-lock.json
**Issue #:** 
Security Update Dependabot for axion requesting v0.21.1
update amplify-js/storage version from 3.3.6 to 3.3.16
update amplify-js/api-rest version from 1.2.6 to 1.2.16
**Testing**
Yes
> Dependabot security fix axios

- CHANGELOG.md
- src/theme/dark.ts
- src/theme/light.ts
**Issue #:** 
Add linkColors for incoming and outgoing chat in chatBubble
**Testing**
Yes
Tested manually
N/A
> Add linkColors for incoming and outgoing chat in chatBubble

- CHANGELOG.md
- src/components/ui/PopOver/index.tsx
Add className to <StyledPopOverMenu> in order to give styling access
**Testing**
Yes
Tested locally using macOS client
Yes
> Add className to <StyledPopOverMenu> in order to give styling access

- src/components/ui/Notification/Notification.stories.tsx
- src/components/ui/Notification/Styled.tsx
- src/components/ui/Notification/index.tsx
- tst/components/ui/Notification/index.test.tsx
There are 3 changes in this PR:
- Add an optional button to accompany the notification message.
- Allow users to optionally override the default icon with a custom element.
- Add an option `children` slot for custom content
**Testing**
2. How did you test these changes? Manually, and with unit tests
3. If you made changes to the component library, have you provided corresponding documentation changes? Yes. The docs are updated as well as more storybook stories.
> optional button in notifications

- CHANGELOG.md
- demo/meeting/src/containers/DevicePermissionPrompt.tsx
- demo/meeting/src/enums/index.ts
- demo/meeting/src/utils/TestSound.tsx
- src/hooks/sdk/docs/useDevicePermissionStatus.stories.mdx
- src/hooks/sdk/useDevicePermissionStatus.tsx
- src/index.ts
- src/providers/MeetingProvider/MeetingManager.ts
- src/types/index.ts
**Issue #:** 
Change the permission type from `string` to `DevicePermissionStatus`.
**Testing**
Yes
Sanity test in demo app
> Strictly enforce DevicePermissionStatus type and export hook from library

- CHANGELOG.md
- src/components/sdk/RosterAttendee/index.tsx
**Issue #:** 
#347 
Spreading before mic prop prevents anyone from passing a custom mic to the component
**Testing**
> Fix RosterAttendee overriding mic prop

- CHANGELOG.md
- src/components/ui/Modal/Modal.stories.tsx
- src/components/ui/Modal/ModalButtonGroup.tsx
- src/components/ui/Modal/ModalContext.tsx
- src/components/ui/Modal/ModalHeader.tsx
- src/components/ui/Modal/index.tsx
- src/hooks/useClickOutside/index.tsx
- tst/components/ui/Modal/ModalButtonGroup.test.tsx
- tst/components/ui/Modal/ModalHeader.test.tsx
- tst/components/ui/Modal/index.test.tsx
Sometimes a user flow might require a modal that needs to persist. Although there are a few ways to do that with the current modal props, it's a little convoluted, and requires the user to remember to do the following:
- pass `null` to the `onClose` prop
- set `displayClose` to false in the ModalHeader
- ensure that `ModalButtons` do not set `closesModal` to true
Introducing the `dismissible` prop will allow all of the above to be handled via a single prop. I also cleaned up the modal stories by using a `Heading` component.
**Testing**
2. How did you test these changes? manually and with unit tests
3. If you made changes to the component library, have you provided corresponding documentation …
> Optional prop to prevent dismissing the Modal component

- src/theme/light.ts
It's been discovered that the chat bubbles don't meet the contrast level to be considered accessible. 
**Testing**
2. How did you test these changes? using the deque accessibility plugin
3. If you made changes to the component library, have you provided corresponding documentation changes? no
> use main primary theme color for accessible chat content

- CHANGELOG.md
- package-lock.json
- src/components/ui/Button/Button.stories.tsx
- src/components/ui/Button/IconButton.tsx
- src/components/ui/Button/Styled.tsx
- src/components/ui/ControlBar/Styled.tsx
- src/components/ui/Modal/ModalHeader.tsx
- src/components/ui/Navbar/Navbar.stories.tsx
- src/components/ui/Navbar/NavbarHeader.tsx
- src/components/ui/Navbar/NavbarItem.tsx
- src/components/ui/Navbar/Styled.tsx
- src/components/ui/Navbar/index.tsx
- src/components/ui/icons/Svg.tsx
- tst/components/ui/Button/IconButton.test.tsx
- tst/components/ui/Navbar/NavbarItem.test.tsx
This would be a breaking change as it changes the API contract of the `NavBar` component.
Optionally allow the `IconButton` component to render another element via a `badge` prop.
Refactor the `NavBarItem` component so that it use `IconButton` directly, and accept `children` as content for a `PopOver`. (this is the breaking change)
Optionally prevent responsive styles for the `NavBa`r by introducing a responsive prop that developers can use to keep the `NavBa`r at a static width throughout different breakpoint sizes.
Testing
**Testing**
By submitting this pull …
> refactor NavBar

- CHANGELOG.md
- demo/chat/package-lock.json
- demo/chat/package.json
- demo/meeting/package-lock.json
- demo/meeting/package.json
- package-lock.json
- package.json
- src/components/sdk/MicrophoneActivity/index.tsx
- src/components/ui/Chat/MessageAttachment/Styled.tsx
- src/components/ui/Chat/MessageAttachment/index.tsx
- src/hooks/sdk/useAttendeeAudioStatus.tsx
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/280
- Update the `realtimeUnsubscribeFromVolumeIndicator` method to optionally receive a `callback` param to match the interface updated in the `amazon-chime-sdk-js@2.4`.
- Update the meeting demo application to use the new callback param which no longer causes active speaker detection to stop after closing the roster.
**Testing**
Yes
Updated the demo application and saw active speaker detection working after unsubscribing from volume indicators (closing the roster).
Yes
By …
> Update realtimeUnsubscribeFromVolumeIndicator to receive callback param

- CHANGELOG.md
- package-lock.json
- src/components/ui/icons/Caution/Caution.stories.tsx
- src/components/ui/icons/Caution/index.tsx
- src/components/ui/icons/Caution/styled.tsx
Recent use cases have prompted the need to display the `Caution` icon in states other than the default one. This change allows for 2 new variants for 'warning' and 'error' states, with the code written in a way that will allow for future variants. 
**Testing**
2. How did you test these changes? unit tests, manually and running release
> Add style variants to Caution icon

- CHANGELOG.md
- demo/meeting/package-lock.json
- demo/meeting/src/utils/TestSound.tsx
- demo/meeting/src/utils/VersionLabel.tsx
- package-lock.json
- src/components/sdk/MeetingControls/AudioOutputControl.tsx
- src/hooks/sdk/useSelectAudioOutputDevice.tsx
- src/providers/DevicesProvider/AudioInputProvider.tsx
- src/providers/LocalAudioOutputProvider/index.tsx
- src/providers/MeetingProvider/MeetingManager.ts
- src/utils/device-utils.ts
**Issue #:** https://github.com/aws/amazon-chime-sdk-component-library-react/issues/365
**Description of changes:** 
- Guarded `chooseAudioOutputDevice` API by a call to `supportsSetSinkId`.
- Print out the `amazon-chime-sdk-js` version in the meeting demo app.
**Testing**
Tested by running the meeting demo app. Hard coded `amazon-chime-sdk-js` to `2.4.0` & `1.22.0` to verify it works for both `amazon-chime-sdk-js` v1.x & v2.x
It would be updated in the V2 migration doc.
> Fix meeting manager to handle `setSinkId` error

- CHANGELOG.md
- src/components/ui/Navbar/NavbarItem.tsx
- src/components/ui/Navbar/Styled.tsx
**Issue #:** NA
Build was failing for the meeting demo app because of some unused imports. Removed those imports to fix the build.
**Testing**
2. How did you test these changes? By running `npm run build` in `demo/meeting` folder
3. If you made changes to the component library, have you provided corresponding documentation changes? Not required. Its just removing unused imports
> Removed unused import statements from NavBar

- CHANGELOG.md
- src/components/ui/Navbar/NavbarItem.tsx
**Issue #:** 
Allow property passthrough to IconButton in NavbarItem
**Testing**
> Allow property passthrough to IconButton in NavbarItem

- CHANGELOG.md
- src/providers/MeetingProvider/MeetingManager.ts
**Issue #:** 
#409
Check that user has a video input device before 
**Testing**
- Joined meeting on PC with no web camera device
- Joined Meeting with web cam device
> Check for video inputs before requests video permission

- src/components/ui/PopOver/PopOver.stories.tsx
- src/components/ui/PopOver/index.tsx
- tst/components/ui/PopOver/index.test.tsx
**Issue #:** 
See title. This should solve the issues like being unable to select multiple emojis before closing. 
**Testing**
Yes
Unit and storybook
Yes
> Allow PopOver to receive multiple clicks before closing

- CHANGELOG.md
- src/providers/RosterProvider/index.tsx
Render roster without waiting for getAtendee callback so that getAttendee callback does not block roster component from populating
**Testing**
2. How did you test these changes? Manually verified in the meeting demo app by adding a sleep timer in the getAttendee callback and checked that the roster was updated before the attendee name came back.
> Render roster without waiting for getAtendee callback

- CHANGELOG.md
- src/components/ui/MicVolumeIndicator/index.tsx
**Issue #:** 
#423 
- Fixed the `MicrophoneActivity` component's `className` prop overridden by the `MicVolumeIndicator` component `className`.
**Testing**
2. How did you test these changes? Tested by running and testing locally in the demo meeting app.
3. If you made changes to the component library, have you provided corresponding documentation changes? No update required.
> Override default className with prop className

- demo/meeting/check-version.js
- demo/meeting/package.json
**Issue #:** 
Add a SDK version checking script that will validate that the SDK node module installed on the components library is supported.
**Testing**
2. How did you test these changes? running the script locally
3. If you made changes to the component library, have you provided corresponding documentation changes? no
> Add sdk version validation check on components demo

- src/hooks/useFocusIn/index.tsx
- src/hooks/useMouseMove/index.tsx
When `useMouseMove` and `useFocusIn` are unmounted, we don't currently clean up the timeouts that are set on the `ref` object. This change will ensure that the timeouts are removed. 
**Testing**
2. How did you test these changes? manually in a browser
3. If you made changes to the component library, have you provided corresponding documentation changes? n/a, this is a bug fix
> clean up timeouts when hooks are unmounted

- CHANGELOG.md
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/MeetingProvider/index.tsx
**Issue #:** 
None.
- Update `MeetingProvider` and corresponding documentation to support
re-usable `MeetingManager` instance.
**Testing**
2. How did you test these changes? Tested running the demo app locally.
> Add support for re-usable MeetingManager

- CHANGELOG.md
- src/components/ui/WithTooltip/index.tsx
**Issue #:** 
Fix removeEventListener bug of WithTooltip
**Testing**
Yes
Ran release script locally and manual test
Yes
> Fix removeEventListener bug of WithTooltip

- CHANGELOG.md
- src/providers/LocalAudioOutputProvider/index.tsx
**Issue #:** 
Basically the issue is we do not reset `isAudioOn` back to true when the `LocalAudioOutputProvider` is unmounted. Hence, we start a new meeting or re-join the same left meeting the `isAudioOn` remains `false` (the speaker will show disabled which should be enabled when you join a meeting) if disabled while leaving earlier meeting.
- To fix this, we need to reset the `isAudioOn` state to `true` when `LocalAudioOutputProvider` unmounts.
**Testing**
2.1 Run the demo/meeting app.
2.2 Join a meeting.
2.3 After you join the meeting, a meeting controls bar with mute button, video button appears at the bottom of the screen in the middle. You will see a …
> Reset isAudioOn to true when LocalAudioOutputProvider unmounts

- CHANGELOG.md
- src/providers/RosterProvider/index.tsx
**Issue #:** 
After #427, we will render a nameplate while waiting for result from getAttendee. However, if the attendee leaves before getAttendee callback finishes, the placeholder nameplate will be removed from the roster.  When getAttendee callback finishes, the attendee name will be updated and shown in the roster incorrectly.
This PR adds a check to make sure that the attendee is still on roster after getAttendee callback finishes before updating the roster.
**Testing**
2. How did you test these changes? Manually added a wait time of 5s in getAttendee callback in the meeting demo, and did the following:
- Attendee A joined a meeting.
- Attendee B joined a meeting and left right away.
- Make …
> Fix getAttendee populate name even after the attendee has left the meeting

- demo/chat/src/components/ChannelModals/NewChannelModal.css
Swap the help text for private and public channel so they are correct.
**Testing**
2. How did you test these changes? Manually verify the help text in chat demo app.
> Fix chat demo new channel help text

- CHANGELOG.md
- src/components/sdk/MeetingControls/AudioInputControl.tsx
- src/components/sdk/MeetingControls/AudioOutputControl.tsx
- src/components/sdk/MeetingControls/ContentShareControl.tsx
- src/components/sdk/MeetingControls/VideoInputControl.tsx
- src/components/ui/Chat/ChatBubble/ChatBubbleContainer.tsx
- src/components/ui/ControlBar/ControlBar.mdx
- src/components/ui/ControlBar/ControlBar.stories.tsx
- src/components/ui/ControlBar/ControlBarButton.tsx
- src/components/ui/Navbar/Navbar.mdx
- src/components/ui/Navbar/NavbarItem.tsx
- src/components/ui/Roster/PopOverMenu.tsx
- src/components/ui/Roster/Roster.mdx
- src/components/ui/Roster/Roster.stories.tsx
- src/components/ui/Roster/RosterHeader.tsx
- src/components/ui/WithTooltip/WithTooltip.stories.mdx
- src/components/ui/WithTooltip/index.tsx
- src/index.ts
- tst/components/ui/ControlBar/ControlBarButton.test.tsx
- tst/components/ui/ControlBar/ControlBarItem.test.tsx
- tst/components/ui/ControlBar/index.test.tsx
**Issue #:** 
#445 
The `WithTooltip` has a lot of flaws. The HOC may share the label prop with other components, and other components internally relying on it don't pass the container ID to the HOC.
This change...
- adds a `tooltipText` prop that can alternatively be used in place of `label`. Label will continue to be used as a fallback to avoid breaking changes
- Logs a warning if no container element is found
- Fixes some `WithTooltip` consumers that didn't allow a way for to pass a container ID
- Adds some docs around `WithTooltip`
**Testing**
Manually, and by syncing the changes to Chime and seeing if there was any breakage. I did not see any
3. If you made …
> Add docs, minor flexibility to WithTooltip HOC

- CHANGELOG.md
- demo/chat/src/backend/serverless/template.yaml
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/types.ts
**Issue #:** 
Reflect the support for allowing arbitrary to be passed to RosterProvider.
Add index signature in AttendeeResponse.
**Testing**
Yes, passed all the test.
Return flatten and nested arbitrary from api.ts in meeting demo, these arbitrary can be access by RosterProvider, and be displayed in RosterCell UI component.
> Support extra properties attendee response

- CHANGELOG.md
- demo/meeting/package-lock.json
- demo/meeting/package.json
- rollup.config.js
**Issue #:** 
The component library depends on uuid package which in turn depends on crypto but rollup did not know how to resolve this dependency (whether it comes from browser or node).
Currently, we use external to not include crypto in the result rollup but it causes uuid to use node implementation of crypto in the bundle file (The code copied from index.esm.js below use randomFillSync which is a method in node).
```
if (poolPtr > rnds8Pool.length - 16) {
crypto.randomFillSync(rnds8Pool);
poolPtr = 0;
}
```
In webpack version previous to 5, this is fine because they include polyfills for Node but it is no longer the case for Webpack 5.
Using component library with webpack would result in this error:
```
Module not found: Error: Can't resolve 'crypto' in '<your …
```
> Set node resolve to browser

- CHANGELOG.md
- src/components/sdk/DeviceSelection/CameraSelection/QualitySelection.tsx
- src/components/sdk/MeetingControls/AudioInputControl.tsx
- src/components/sdk/MeetingControls/ContentShareControl.tsx
- src/components/ui/icons/Microphone/index.tsx
- src/components/ui/icons/ScreenShare/index.tsx
**Issue #:** 
Allow localisation of the following properties:
- Microphone icon
- tooltip when muted
- tooltip when unmuted
- Screen Share icon
- tooltip
- Video Quality dropdown
- label for unselected video quality
**Testing**
Yes
All the tests passed from the above script, and we manually verified that when we overrode the configuration in a project that uses these components, it had the desired effect.
We've added comments alongside the new properties, which are written consistently with existing comments.
By submitting this pull request, I confirm that my …
> Allowing localisation of labels within Microphone, Share Screen and Video Quality components

- src/providers/MeetingProvider/MeetingManager.ts
**Issue #:** None
Tiny fix to an error message in `MeetingManager`. I'm pretty certain this error message should say *input* instead of *output*.
**Testing**
No (in the vacuous sense, I didn't even try)
Guesswork
N/A
> Fix selectAudioInputDevice error message

- .github/workflows/deploy.yml
- package-lock.json
**Issue #:** 
- Last deployment workflow has failed with below error:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! Cannot read property 'match' of undefined
```
- Added node version to be `15.x` while the deployment job runs.
**Testing**
2. How did you test these changes? Have to test by merging the workflow in.
> Fix deployment workflow to use node 15

- CHANGELOG.md
- demo/meeting/package-lock.json
- package-lock.json
- src/components/sdk/PreviewVideo/PreviewVideo.stories.mdx
- src/components/sdk/PreviewVideo/index.tsx
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/314
This fixes a bug where the VideoPreview component would not stop the media stream on the video preview video element because a ref was being unset before the unmount method could use the value of the ref.
Instead of using the ref in the unmount method - we just save the ref value locally, and then use the variable when we unmount. 
**Testing**
yes
Join a meeting, verify that the light next to the webcam indicating an active media stream is turned off when we join the meeting. Then, turn the camera on while in the meeting, and verify that the light next to the webcam is turned …
> Fix videopreview component bug

- CHANGELOG.md
- demo/meeting/src/providers/ErrorProvider.tsx
- demo/meeting/src/views/DeviceSetup/index.tsx
- src/providers/DevicesProvider/AudioInputProvider.tsx
- src/providers/DevicesProvider/VideoInputProvider.tsx
- src/providers/DevicesProvider/docs/AudioInputProvider.stories.mdx
- src/providers/DevicesProvider/docs/VideoInputProvider.stories.mdx
- src/providers/DevicesProvider/docs/useAudioInputs.stories.mdx
- src/providers/DevicesProvider/docs/useVideoInputs.stories.mdx
- src/providers/MeetingProvider/MeetingManager.ts
- src/types/index.ts
**Issue #433 :** 
Fix several typos. 
Add observer to `selectAudioInputDeviceError` and `selectVideoInputDeviceError` to deliver the error from SDK level to client application level.
When calling the `meetingManager.selectVideoInputDevice()/selectAudioInputDevice()`
* If there is an error, assign the error to `selectVideoInputDeviceError`/`selectAudioInputDeviceError`, and publish it
* If there is no error, set the `selectVideoInputDeviceError`/`selectAudioInputDeviceError` to `null`, and publish it
Error can be accessed through `useVideoInput`/`useAudioInput` hook. 
**Testing**
Yes
Mock a non-existent device for both `VideoInputProvider` and `AudioInputProvider`, …
> Add Observer to select input device error

- CHANGELOG.md
- package-lock.json
Bump hosted-git-info version by running `npm update hosted-git-info`
This is fine to do since hosted-git-info is a dependency of normalize-package-data which allows minor version update (^2.1.4).
**Testing**
2. How did you test these changes? npm test and regression check the meeting demo
> Bump hosted git info version

- CHANGELOG.md
- src/theme/dark.ts
**Issue #:** 
#497 
When `IconButton` is used in dark theme, the static border is set to 0,
while in light theme it is set to 0.03125rem.
On hover, in dark theme, the border is set to 0.03125rem which results
into a jumpy behavior as the dimension changes from 0 to 0.03125rem.
This change sets the border color to be transparent and matches
the border dimension with light theme.
**Testing**
2.1 Run demo/meeting app and join the meeting.
2.2 Before this change if you hover over icon buttons in the roster header (where there is a search icon) the roster header kind of shift a little due to a border changing from 0 to 0.03125rem as explained.
2.3 After this change …
> [Do not merge] Correct icon button border in dark theme

- CHANGELOG.md
- src/hooks/sdk/docs/useDevicePermissionStatus.stories.mdx
**Issue #506 :** 
Update device permission doc to actually use device permission hook instead of meeting status.
**Testing**
2. How did you test these changes? Just documentation update.
> Fix device permission doc

- demo/chat/package-lock.json
- demo/meeting/package-lock.json
- package-lock.json
Bump `ws` depdedency to `6.2.2` and `7.4.6`.
**Testing**
2. How did you test these changes? Ran the meeting and chat demo and verified that they rendered correctly.
> Bump ws dependency version

- src/components/introduction.stories.mdx
**Issue #:** N/A
* Fix the broken links of global introduction page in the story book
**Testing**
2. How did you test these changes? Go to the global introduction in story book, click links listed on the page. It should navigate to the corresponding page.
3. If you made changes to the component library, have you provided corresponding documentation changes? It is a doc change.
> Fix the broken links in story book

- .github/workflows/deploy.yml
- .github/workflows/publish.yml
Move storybook deploy to when PR merge instead of when publishing to NPM as before.
**Testing**
> Move storybook deploy to when PR merge

- demo/meeting/src/components/RosterAttendeeWrapper.tsx
- demo/meeting/src/containers/MeetingRoster.tsx
**Issue #531 :** 
Move the `key` prop from children `RosterAttendee` to parent `RosterAttendeeWrapper`.
**Testing**
Yes
Check the meeting demo, it renders correctly and the warning disappears.
> Fix missing key prop in RosterAttendeeWrapper

- demo/meeting/serverless/template.yaml
Enable SSE for SQS queue in serverless demo following these resouces:
- https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-notifications.html
- https://docs.amazonaws.cn/en_us/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-lambda-function-trigger.html
**Testing**
- Deployed the meeting app with this template change and observed default SSE added to the queue created by the CF template with the custom CMS Key with the correct permissions for chime services.
- Tested joining, re-joining, ending and leaving, video on/off.
- Verify in the lambda cloudwatch log that we received meeting events.
3. If you made changes to the component library, have you …
> [Demo] Enable sse for SQS in meeting serverless demo

- demo/meeting/serverless/template.yaml
Add the stack name to the kms alias in serverless template to make sure its unique for each stack.
**Testing**
Manually deployed another stack in the same aws account and verified that it worked.
> [Demo] Add stack name to kms alias in serverless demo

- CHANGELOG.md
- demo/meeting/src/app.tsx
- demo/meeting/src/containers/DevicePermissionControl/DevicePermissionControl.tsx
- demo/meeting/src/containers/DevicePermissionControl/Styled.tsx
- demo/meeting/src/containers/DynamicMeetingControls/Styled.ts
- demo/meeting/src/containers/DynamicMeetingControls/index.tsx
- demo/meeting/src/containers/MeetingForm/index.tsx
- demo/meeting/src/providers/AppStateProvider.tsx
- demo/meeting/src/types/index.ts
- demo/meeting/src/views/Meeting/index.tsx
- src/index.ts
- src/providers/DevicesProvider/AudioInputProvider.tsx
- src/providers/DevicesProvider/AudioOutputProvider.tsx
- src/providers/DevicesProvider/VideoInputProvider.tsx
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/MeetingProvider/types.ts
- src/types/index.ts
**Issue #379 :**
- Add controls to device permission request in `DeviceProvider` and `MeetingManager` to suppress the permission request, and invoke it.
- Add a checkbox in `MeetingForm` to allow use join the meeting  without device preview process.
- Add a `DevicePermissionControl` component, which is used in `MeetingControls`.
- Change the `MeetingControls` to be rendered conditionally based on `devicePermissionStatus`.
**Testing**
Yes
* User joins a meeting without selecting "Join w/o Audio and Video"
* Device permission prompt pops up for audio and video device
* Device setup page works as usual and join the meeting
* Check `MeetingControl` works as usual
* User …
> Delay device permission request

- demo/meeting/src/containers/DevicePermissionControl/DevicePermissionControl.tsx
- demo/meeting/src/containers/DynamicMeetingControls/index.tsx
- demo/meeting/src/containers/MeetingForm/index.tsx
**Issue :** 
Several import statements import enum `DeviceLabels` from a wrong place.
Fix the import statements.
**Testing**
Yes
Run meeting demo and it renders correctly and functions well.
N/A
> Fix wrong import statement in meeting demo

- src/providers/MeetingProvider/MeetingManager.ts
**Issue:**
The device is not selected when user joins a meeting in Firefox. 
* The `enumerateDevices()` in original  line 348 doesn't `await` the `getUserMedia()` call from `updateDeviceLists` and `DeviceProvider`
* So the `hasAudioInput`, `hasAudioOutput` and `hasVideoInput` keep a `false` status 
* After user navigates to `DevicePage`, although the devices are listed there, but none of them is selected. 
* This cause no video preview and no microphone activity in `DevicePage`. 
* After user joins the meeting, the selected device for audio input and video input are 'None'.
Slightly modified the logic of checking the device label in `MeetingManager`.
Replace the
```ts
const devices = await navigator.mediaDevices.enumerateDevices();
```
with 
```ts …
```
> Fix the issue that the device is not selected in Firefox

- CHANGELOG.md
- src/hooks/sdk/docs/useDevicePermissionStatus.stories.mdx
**Issue #:** 
The `useDevicePermissionStatus` hook cannot read the device permissions from the browser due to browsers' lack of support of such a querying function.
Add doc in storybook to explain the limitation of the `useDevicePermissionStatus' hook.
**Testing**
Yes
N/A, doc changes
N/A
> Add explanation for the limitation of the `useDevicePermissionStatus'

- CHANGELOG.md
- src/components/sdk/PreviewVideo/PreviewVideo.stories.mdx
- src/components/sdk/PreviewVideo/index.tsx
- src/providers/LocalVideoProvider/docs/LocalVideoProvider.stories.mdx
- src/providers/LocalVideoProvider/docs/useLocalVideo.stories.mdx
- src/providers/LocalVideoProvider/index.tsx
- src/types/index.ts
**Issue #529 :** 
If `PreviewVideo` and `LocalVideo` are used at the same time, unmounting `PreviewVideo` leads to the closing of `LocalVideo` stream, but the `isVideoEnabled` is still `true`, resulting a blank `LocalVideo` tile, and the status of the video button in MeetingControl is still on.
- Add `setIsVideoEnabled` in `useLocalVideo` hook to set the value of the `isVidelEnabled`.
- Set the value of `isVideoEnabled` to `false` after unmounting the `PreviewVideo` to correct its status.
**Testing**
Yes
- Run meeting demo and make sure`LocalVideo` and `PreviewVideo` work well, the states are correct.
- Modify meeting demo to allow opening a dialog for …
> Fix the issue isVideoEnabled is not correct after unmounting the PreviewVideo

- demo/meeting/src/containers/MeetingForm/index.tsx
**Issue #:** 
- Mistakenly, added `NoOpEventReporter` when enable event reporting = `true`. Should have been the opposite.
- Updated the conditional check.
**Testing**
- Ran the demo locally as well as deployed serverlessly to test if checking un-checking "Enable event reporting" works as expected.
- More testing steps are available in PR #554.
- This is a demo change only.
> Fix demo event reporting check

- src/providers/DevicesProvider/docs/AudioInputProvider.stories.mdx
- src/providers/DevicesProvider/docs/VideoInputProvider.stories.mdx
- src/providers/DevicesProvider/docs/useAudioInputs.stories.mdx
- src/providers/DevicesProvider/docs/useVideoInputs.stories.mdx
**Issue #:** 
Find typo in some .mdx files when using the storybook
Fix with the correct close tags
**Testing**
yes
make syntax correct
N/A
> fix: fix close tag typo in .mdx file

- CHANGELOG.md
- rollup.config.js
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/569
We enable the `browser` flag in [@rollup/plugin-node-resolve](https://www.npmjs.com/package/@rollup/plugin-node-resolve), so the Rollup includes the browser version of the `uuid` module in the final output file. 
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/dcc25b6833f79d160056a217e6ad1890958816da/rollup.config.js#L24-L26
In this PR, we exclude the `uuid` module from the output file, so the Chime SDK React Components Library uses the `uuid` installed in the customer's `node_modules`.
**Testing**
1. Have you successfully run `npm run build:release` locally? Yes. Running the command keeps generating the `package-lock.json` with lockfileVersion 1 (npm …
> Exclude the uuid module from the Rollup bundle

- src/components/ui/VideoGrid/Styled.tsx
- src/components/ui/VideoGrid/VideoGrid.mdx
**Issue #:** 
Adding UI change (VideoGrid component) to support 25 remote video tiles
Sceenshots of new video grid layout:
[25-video-grid-layout.zip](https://github.com/aws/amazon-chime-sdk-component-library-react/files/6888532/25-video-grid-layout.zip)
**Testing**
yes
Locally tested 25 remote video tiles with featured content share using JS SDK Doc (https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/ui-components-video-videogrid--video-grid)
Locally tested 25 remote video tiles using the meeting demo;
Will request QA team to help testing as well. 
3. If you made changes to the component library, have you provided corresponding documentation …
> Add UI support of 25 video tiles

- CHANGELOG.md
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/MeetingProvider/index.tsx
- src/providers/MeetingProvider/types.ts
**Issue #:** 
User wants to set the `Logger` and `VideoDownlinkBandwidthPolicy` for the meeting session.
* Add an option parameter in `MeetingConfig` to pass in a `VideoDownlinkBandwidthPolicy` instance to customize the downlink policy of the meeting
* Add an option parameter in `MeetingConfig` to pass in a `Logger` instance to customize the `Logger` of the meeting
**Testing**
Yes
Check the console logger and downlink policy is set correctly.
Yes
> Add support to customize the downlink policy of the meeting

- CHANGELOG.md
- src/providers/MeetingProvider/MeetingManager.ts
**Issue #:** 
* [Bug] When `leave` method in `MeetingManager` is called, the `logger` and `videoDowlinkBandwidthPolicy` will be set to `undefined` unexpectedly
* The way `MeetingManager` stores input parameter and initializes `MeetingSession` needs to be improved
* In `MeetingManager` add a private property `config` to store the `config` object passed in
* Remove `logLevel`, `postLoggerConfig`, `simulcastEnabled`, `videoDownlinkBandwidthPolicy` and `logger` properties
* Use the newly added property `config` instead of the removed properties to initialize the `MeetingSession`
**Testing**
Yes
* Run the meeting demo and check that the bug is fixed, the `MeetingManager` …
> Improve the way MeetingManager initializes MeetingSession

- CHANGELOG.md
- src/providers/MeetingProvider/MeetingManager.ts
**Issue #:** 
- Add `ManagerConfig` object to `MeetingManager`.
- Move object creation/initialization from `MeetingManager` constructor to `initializeMeetingSession` method.
- Reverts earlier commit (#586) where I did not checked for backward compatibility.
- This PR addresses the required changes with backward compatability.
**Testing**
Yes.
By running, the meeting demo, tested general flow.
> Fix meeting manager init

- src/index.ts
**Issue #:** [#601](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/601)
Export `useVoiceFocus` hook, type `RosterAttendeeType` and `RosterType`.
**Testing**
2. How did you test these changes? Run `npm run build` and pack the component as a tar file, then install the tar file in the meeting demo. Import the `useVoiceFocus` from React library,  it works as expected.
> Export useVoiceFocus hook

- CHANGELOG.md
- src/providers/MeetingProvider/MeetingManager.ts
**Issue #:** [#605](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/605)
The `audioVideoDidStop()` has not been called when attendee leaves/ends the meeting. The root issue is that we remove all observers before the `audioVideoDidStop()` being called in the `audioVideo.stop()`. So remove the audio video observers in the `audioVideoDidStop()` function instead of `leave()` function.
**Testing**
- Join the meeting
- Leave meeting
- `audioVideoDidStop` is called since there is a log `[MeetingManager audioVideoDidStop]` in the develop tool.
- Join the meeting
- End the meeting for all
- `audioVideoDidStop` is called again.
- Join the meeting …
> Remove audio video observers in the audioVideoDidStop()

- scripts/prebuild.js
**Issue #:** 
- The changelog checking is broken and the `npm run build:release` will succeed even if you change something in `src` directory and do not include CHANGELOG for it.
- This PR fixes it.
- Running `npm run build:release` runs `prebuild.js` which checks for `src/` changes and needs a `CHANGELOG` update for those changes.
- The commit files is an array and we do not check for each file in the array hence the check is broken and results into a success even if we change files in `src` directory.
- I just updated the check to go through all files.
**Testing**
2.1. Changed `src/providers/MeetingProvider/MeetingManagar.ts` but did not add changelog for it. …
> Fix CHANGELOG check script

- scripts/update-sdk-version.js
**Issue #:** 
- NPM install fails in GitHub action as it uses ubuntu machine when installing `fsevents`.
- The `fsevents` has a OS field in `package-lock` which supports `darwin` hence installation fails in `ubuntu` VMs.
- We use node 16 in GA which is not stable, some versions don't break (16.3.0 - 16.8.0) while some do (16.9.0 onwards).
- To avoid above issue, remove `package-lock` to do a fresh installation when GA runs in `ubuntu` VM.
**Testing**
1. Have you successfully run `npm run build:release` locally? Not needed.
2. How did you test these changes? Will test in GA. But verified in Cloud 9 ubuntu VM.
By submitting this pull request, I confirm that …
> Remove package-lock to fix npm install in GitHub actions

- .gitignore
- CHANGELOG.md
- src/index.ts
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/MeetingProvider/types.ts
- Add `activeSpeakerPolicy` and `videoUplinkBandwidthPolicy` in meeting manager config to allow builders to pass in 
custom policies.
- Allow passing in config in `meetingManager.join` to allow more flexibility.
- Export MeetingManagerConfig object.
**Testing**
- Verified passing custom active speaker policy and video uplink bandwidth policy to the React meeting demo.
> Add activeSpeakerPolicy and videoUplinkBandwidthPolicy in meeting manager config

- CHANGELOG.md
- src/components/sdk/MeetingControls/AudioInputVFControl.tsx
- src/providers/DevicesProvider/AudioInputProvider.tsx
**Issue #:** Amazon Voice Focus does not get applied on new audio-devices when connected mid-meeting.
1. This issue only happens in Chrome, since only Chrome have the `default` device. If user selects a specific device or uses other browser such as Safari/FireFox, the current device won't be changed to the new device automatically which is expected.
2. The issue only happens when the new device is AirPods, since only AirPods have two steps to be the current device. When you open the container, AirPods will be shown in the device dropdown list; When you put AirPods on your ears, the current device will be set to AirPods automatically. However, the VF dropdown list only gets updated at the first step, since the length of available devices changes, and it won't be …
> Fix the issue that Amazon Voice Focus does not get applied on new devices in the middle of meeting

- CHANGELOG.md
- src/providers/DevicesProvider/AudioInputProvider.tsx
**Issue #:** Amazon Voice Focus does not get applied on new audio-devices when connected mid-meeting.
Add Amazon Voice Focus to the default device when a new blue tooth device is plugged in during the meeting. 
**Testing**
2. How did you test these changes? Open two Chrome tabs, select the default device as audio input and disable speaker in one tab, disable microphone and set built in device as speaker in another tab. Turn on Amazon Voice Focus in the first tab, and apply a new device (AirPods), the current device changes as AirPods. Then make some background noice, we don't hear any noice from the second tab, it shows Amazon Voice Focus is enabled in the first tab.
3. If you made changes to the …
> Add Amazon Voice Focus to default device

- CHANGELOG.md
- src/hooks/sdk/docs/useMeetingStatus.stories.mdx
- src/providers/MeetingProvider/MeetingManager.ts
- src/types/index.ts
**Issue #:** 
We don't want to set meetingStatus to Loading - this is the same state we use when we are joining a meeting. It can be confusing for builders if they are listening to this Loading state. 
**Testing**
yes
Start a meeting, leave a meeting.
N/a
> Fix bug regarding setting meetingStatus to Loading when leaving meeting

- CHANGELOG.md
- src/hooks/sdk/docs/useMeetingStatus.stories.mdx
- src/hooks/sdk/useMeetingStatus.tsx
- src/providers/MeetingProvider/MeetingManager.ts
- src/types/index.ts
**Issue #:** 
Introduce a Terminal state to MeetingStatus - this will receive any meeting statuses from the Amazon Chime SDK for Javascript and bubble them up into the React Library's concept of Meeting Status. 
**Testing**
yes
From the demo app, disconnect from meeting to trigger terminal failure. 
Yes
> Add MeetingStatus Terminal State

- CHANGELOG.md
- src/providers/LocalVideoProvider/index.tsx
**Issue #626 :** 
Remove the observer in `useEffect` cleanup process in `LocalVideoProvider`.
**Testing**
Yes
Tried to reproduce the memory leak issue by creating a new component that use the `useLocalVideo` hook, but failed to reproduce it. So just successfully run `npm run build:release`. Anyway we should remove this observer when the provider is unmounted.
meeting demo
> Fix memory leak in LocalVideoProvider

- CHANGELOG.md
- src/providers/LocalVideoProvider/index.tsx
**Issue #626:** 
Store the listener in an variable `observer`, add and remove this event listener using the reference to `observer`.
**Testing**
Yes
I can't reproduce the issue in our meeting demo. I use TypeScript play ground to mimc the testing code, and confirm the observer can be added and removed in the `Set`.
N/A
> Remove AudioVideoObserver in LocalVideoProvider

- CHANGELOG.md
- src/providers/MeetingProvider/MeetingManager.ts
**Issue #:** 
NA
- Fix `eventDidReceive` observer removal.
**Testing**
2. How did you test these changes? Tested by raising this PR: https://github.com/aws-samples/amazon-chime-sdk/pull/67 against the demo app.
> Correctly remove event observer

- src/theme/styled.ts
fixes #588
Renamed `src/theme/styled.d.ts` to `src/theme/styles.ts` so that the build will generate the `styled.d.ts` file for distribution.
Reference: https://betterstack.dev/blog/publishing-type-definitions-with-npm-package/#heading-write-type-definitions-in-ts-files
**Testing**
YES
Ran `npm pack` and then imported it into an app to verify transpiling with `tsc`
N/A
> Rename theme file so that it properly generates definition file

- CHANGELOG.md
- src/hooks/sdk/docs/useSelectVideoInputDevice.stories.mdx
**Issue #:** 
#604 
- Add documentation on when to use `selectVideo` from `useSelectVideoInputDevice` hook.
**Testing**
Yes.
- Created the provided work-around hook in the react meeting demo and saw whether the LED goes off upon changing the video input devices.
- Added documentation for work-around.
> Update useSelectVideoInputDevice hook documentation and usage example

- CHANGELOG.md
- src/providers/VoiceFocusProvider/docs/VoiceFocusProvider.stories.mdx
- src/providers/VoiceFocusProvider/docs/useVoiceFocus.stories.mdx
**Issue #:** N/A
Update the `VoiceFocusProvider` and `useVoiceFocus` documentation in the storybook. 
* Update the default value of `device`
* Remove `audioInputSelectionToDevice` function since it is not exported from React component library
* Document props, so builders can know how to change `spec`. [Issues 612](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/612)
**Testing**
2. How did you test these changes? 1. Apply the code in the meeting demo and it works as expected. 2. Run story book locally
By submitting this pull request, I confirm that my contribution is …
> Update VoiceFocusProvider and useVoiceFocus in storybook

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/sdk/MeetingControls/VideoInputBackgroundBlurControl.tsx
- src/components/sdk/MeetingControls/docs/AudioInputVFControl.stories.mdx
- src/components/sdk/MeetingControls/docs/VideoInputBackgroundBlurControl.stories.mdx
- src/components/sdk/MeetingControls/index.tsx
- src/index.ts
- src/providers/BackgroundBlurProvider/docs/BackgroundBlurProvider.stories.mdx
- src/providers/BackgroundBlurProvider/docs/useBackgroundBlur.stories.mdx
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/LocalVideoProvider/index.tsx
- src/providers/MeetingEventProvider/index.tsx
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/VoiceFocusProvider/docs/VoiceFocusProvider.stories.mdx
**Issue #:** 
Add the background blur feature to the React Library.
I created one provider - `BackgroundBlurProvider`and one sample component- `VideoInputBackgroundBlurControl`.
I modified `meetingManager.selectVideoInputDevice` to accept `VideoTransformDevice` along with `Device`.
There was also a small fix to initialize `selectedAudioInputTransformDevice` when the meeting is first started. We need to initialize that so that any subscribers get the correct initial value for `selectedAudioInputTransformDevice`
**Testing**
Yes
Locally ran tests
1. Join meeting, turn on video. 
2. Enable background blur
3. Disable BG Blur
4. Enable BG Blur and turn off video, turn on …
> Add Background Blur Provider and VideoInputBackgroundBlurControl component

- CHANGELOG.md
- src/components/sdk/DeviceSelection/CameraSelection/VideoFilterSelection.tsx
- src/components/sdk/DeviceSelection/docs/VideoFilterSelection.stories.mdx
- src/components/sdk/DeviceSelection/index.tsx
- src/components/sdk/MeetingControls/VideoInputBackgroundBlurControl.tsx
- src/components/sdk/PreviewVideo/index.tsx
- src/index.ts
**Issue #:** 
Update PreviewVideo to show the `selectedVideoInputTransformDevice` rather than the `selectedVideoInputDevice`. The difference is that the `selectedVideoInputTransformDevice` can be a regular `Device` but also a `VideoTransformDevice` - that means the PreviewVideo can now show video streams that have been transformed.
Next, add a `VideoFilterSelection` component that will simply create a background blur `VideoTransformDevice` and then call `meetingManager.selectVideoInputDevice` to select the background blur video transform device, thus publishing a new `selectedVideoInputTransformDevice`. The PreviewVideo component will listen to any changes on `selectedVideoInputTransformDevice` and update the video element with that video stream. 
Also, fixes a …
> Update PreviewVideo to support VideoTransformedDevices, and Add VideoFilterSelection component

- CODEOWNERS
**Issue #:**
- Restrict the GitHub PR review notifications to just the JS SDK Dev team.
- Update CODEOWNERS with newly created dev team: https://github.com/orgs/aws/teams/amazon-chime-sdk-js-dev
**Testing**
> Update CODEOWNERS with newly created dev team

- package-lock.json
- package.json
**Issue #:** 
Update JS SDK chime revision to include background blur CPU utilization option.
https://github.com/aws/amazon-chime-sdk-js/pull/1746
**Testing**
Yes
I have local changes for demo and confirmed with using local build
> Update chime js sdk to v2.21.1

- CHANGELOG.md
- src/providers/DevicesProvider/AudioInputProvider.tsx
- src/providers/DevicesProvider/index.tsx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/MeetingProvider/index.tsx
**Issue #:** Amazon Voice Focus does not get applied on new audio-devices when connected mid-meeting.
Add Amazon Voice Focus to the default device when a new blue tooth device is plugged in during the meeting.
This issue only happens in Chrome and when user selects "default" device as the audio input device. 
**Testing**
Should test with the PR of meeting demo: https://github.com/aws-samples/amazon-chime-sdk/pull/70
* Open two Chrome tabs (no Safari, no FF)
* Disable speaker in one tab
* Disable microphone and set built in device as speaker in another tab
* Turn on Amazon Voice Focus in the first tab
* Apply a new device (AirPods)
* The current device changes to …
> Add Amazon Voice Focus to default device in VF provider

- CHANGELOG.md
- src/components/sdk/MeetingControls/VideoInputBackgroundBlurControl.tsx
**Issue #:** 
Fixes a bug where the enable bg blur control is not initially checked when the meeting is started with a video transform device.
Need to initialize the Video Input Background Blur control component with selectedVideoInputTransformDevice because the selectedVideoInputTransformDevice can be a Device or a VideoTransformDevice.
**Testing**
2. How did you test these changes? running the react meeting demo
> Initialize the VideoInputBackgrounBlurControl component with selectedVideoInputTransformDevice

- .eslintignore
- integration/app/test-demo/.gitignore
- integration/app/test-demo/README.md
- integration/app/test-demo/package-lock.json
- integration/app/test-demo/package.json
- integration/app/test-demo/public/meeting.html
- integration/app/test-demo/server.js
- integration/app/test-demo/src/app.tsx
- integration/app/test-demo/src/components/MeetingLeaveControl.tsx
- integration/app/test-demo/src/components/TestApp.tsx
- integration/app/test-demo/src/containers/MeetingControls.tsx
- integration/app/test-demo/src/containers/MeetingForm.tsx
- integration/app/test-demo/src/containers/MeetingRoster.tsx
- integration/app/test-demo/src/index.tsx
- integration/app/test-demo/src/pages/Home.tsx
- integration/app/test-demo/src/pages/RosterTestApp.tsx
- integration/app/test-demo/src/utils/api.ts
- integration/app/test-demo/tsconfig.json
- integration/app/test-demo/webpack.config.js
**Issue #:** 
React Component Library is lack of integration testing coverage.
Create a simple demo App under `/integration` folder.
This simple demo has a main page which serves as a menu. We could reuse the component and container to quickly build a simple test demo according to testing requirement. This menu could redirects the App to the specific test demo to do the testing.
**Testing**
Yes
Try the basic e2e testing and make sure the demo works well.
Yes, in CHANGELOG. And create a simple README to guide on adding new test demo.
By submitting this pull …
> Add simple test demo for integration testing

- scripts/release.js
**Issue #:** 
NA
- This is to update the release script to use the "meeting-dev" branch instead of the "main" branch to create the next demo for testing of next version release.
**Testing**
NA.
Had been tested while creating last release's deployed demo URL.
NA.
> Clone the meeting demo from meeting-dev branch

- integration/utils/DriverFactory.js
- integration/utils/config.js
**Issue #:** 
In the integration test, the default version of the browser is not unified.
Update the default Safari version to latest to make it consistent with Chrome and Safari.
**Testing**
N/A
Try to run the roster test on Sauce Labs using Chrome, Firefox and Safari. Confirmed it works..
N/A
> Update the default version for Safari to latest

- CHANGELOG.md
- src/components/sdk/DeviceSelection/CameraSelection/index.tsx
- src/components/sdk/DeviceSelection/MicSelection/index.tsx
- src/components/sdk/MeetingControls/AudioInputControl.tsx
- src/components/sdk/MeetingControls/AudioInputVFControl.tsx
- src/components/sdk/MeetingControls/VideoInputControl.tsx
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/629
Make the additionalDevices a prop for the media control components. 
**Testing**
yes
Ran it in the meeting demo
yes - I just added a prop with a comment above - they will be picked up by storbybook documentation
> Add additionalDevices as a prop instead of hardcoded

- .eslintrc.json
- .storybook/webpack.config.js
- CHANGELOG.md
- src/components/sdk/DeviceSelection/index.tsx
- src/components/sdk/MeetingControls/VideoInputBackgroundBlurControl.tsx
- src/components/sdk/MeetingControls/VideoInputControl.tsx
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/DevicesProvider/AudioInputProvider.tsx
- src/providers/DevicesProvider/index.tsx
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/MeetingProvider/index.tsx
- src/providers/MeetingProvider/types.ts
**Issue #:** 
Add the `reconnectTimeoutMs` as part of the join parameters and MeetingProvider props so that builders can modify it before joining a meeting.
**Testing**
1. Using the demo app, create a meeting session configuration and pass to the meetingManager.join() function. (timeout = 0sec)
2. Render the MeetingProvider with additional meeting config, including reconnectTimeoutMs (0 sec)
Then, kill the network mid meeting and observe error when reconnect timeout is reached.
By submitting this pull request, I confirm that my contribution is made under …
> Add 'reconnectTimeoutMs' as an optional param when joining a meeting

- integration/README.md
**Issue #:** 
Fix the typo in README of integration test.
* Change the name from `READEME.md` to `README.md`
Change the language of two markdown sections to fix the display issue.
* Before:
* After:
**Testing**
Yes
N/A
N/A
> Improve README of integration test

- CHANGELOG.md
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/MeetingProvider/index.tsx
- src/providers/MeetingProvider/types.ts
Expose the `keepLastFrameWhenPaused` meeting session configuration in React SDK (See https://github.com/aws/amazon-chime-sdk-js/pull/1872 for JS SDK change).
**Testing**
1. Join a meeting with priority based policy and ``keepLastFrameWhenPaused` selected.
2. Throttle the network and make sure that remote videos are paused with last frame.
> Expose keepLastFrameWhenPaused meeting session configuration

- CHANGELOG.md
- src/components/quickStarts.stories.mdx
- src/providers/LocalVideoProvider/docs/LocalVideoProvider.stories.mdx
- src/providers/LocalVideoProvider/docs/useLocalVideo.stories.mdx
- src/providers/LocalVideoProvider/index.tsx
**Issue #:** [Handling meeting video share limit](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/720)
Add `videoAvailabilityDidChange` as an audio observer in `LocalVideoProvider` and a new state `isReachVideoLimit`. There will be a warning when the video limit is reached and an error if a user want to turn on the video in this case. The video button will also be disabled in this case.
**Testing**
Yes
Change the `joinFrame.maxNumOfVideos` to 2 in [JS SDK](https://github.com/aws/amazon-chime-sdk-js/blob/v2.21.0/src/signalingclient/DefaultSignalingClient.ts#L85), so it will reach the video limit when there are two attendees turning on the …
> Add observer videoAvailabilityDidChange in LocalVideoProvider

- CHANGELOG.md
- src/components/sdk/MeetingControls/AudioInputVFControl.tsx
- src/providers/BackgroundBlurProvider/docs/BackgroundBlurProvider.stories.mdx
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/docs/BackgroundReplacementProvider.stories.mdx
- src/providers/BackgroundReplacementProvider/index.tsx
- src/providers/VoiceFocusProvider/index.tsx
- src/types/index.ts
- src/utils/device-utils.ts
**Issue #:** 
Fix a bug with the BG BLur and BG REplacement Providers - the options props were being directly passed to the JS SDK and being mutated - so instead of passing the actual options prop, we pass a copy of the options object to the JS SDK. 
Also, updated the useMemoCompare to be more accurate when comparing the options prop. (For BG BLur and BG Replacement)
Updated the documentation to be a bit more accurate.
I also ran linter to fix syntax issues.
**Testing**
yes
Tested in the demo app. Verified that the old processor is not destroyed anymore. 
Yes
By …
> Fix BG Blur and BG Replacement bug with options prop

- CHANGELOG.md
- src/components/sdk/PreviewVideo/index.tsx
Fix implemented by https://github.com/aws/amazon-chime-sdk-component-library-react/pull/735 - copied to this PR.
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/708
Fix a bug where the PreviewVideo component is not listening to changes to audioVideo - even when we join the meeting and audioVideo changes, we aren't calling startPreviewVideo. This was a regression, as we used to call startVideoPReview when the audioVideo changed. 
**Testing**
yes
Put the VideoPreview component in the Roster integ test app and joined a meeting. Should see the Video Preview component start after joining a meeting. Without this change, I dont see the …
> Fix PreviewVideo bug by listening to audioVideo changes to start the Preview

- src/providers/BackgroundBlurProvider/index.tsx
- tst/providers/BackgroundBlurProvider/index.test.tsx
**Issue #:** #745 
We should have a test to verify that the BackgroundBlurProvider does not re-render unnecessarily in the case that its props are changed by the downstream dependency on BackgroundBlurVideoFrameProcessor in the amazon-chime-sdk-js. This is essentially a follow-up on https://github.com/aws/amazon-chime-sdk-component-library-react/commit/21ba0cfa808c6694c62fc223975fb01f47110728 to add coverage and ensure we don't run into the same problem again.
This is the same as #746 except not forked.
Note that this also adds `jest-useragent-mock` as a dev dependency for ease of testing (needed to mock user agents).
**Testing**
Yes
This pull request adds a test …
> Add BackgroundBlurProvider unit test to verify prop changes (#745)

- integration/app/test-demo/package-lock.json
- integration/app/test-demo/package.json
- integration/package-lock.json
- integration/package.json
**Issue #:** 
Dependencies of integration testing framework is kinda out of date.
* update `chromedriver` to `98.0.1`
* update `geckodriver` to `3.0.1`
* update `amazon-chime-sdk-js` to `2.27.0`
**Testing**
Yes
Run the test demo manually and confirm it works fine.
N/A
> Update webdriver and js sdk version for integration test

- integration/app/test-demo/package-lock.json
- integration/app/test-demo/package.json
**Issue #:** 
Update the version for `amazon-chime-sdk-component-library-react" from 2.11.1 to 2.15.0 in test demo.
**Testing**
N/A
Yes, confirm the test demo works fine.
N/A
> Bump the version of react component library in integration test demo

- integration/app/test-demo/src/app.tsx
- integration/app/test-demo/src/components/TestApp.tsx
- integration/app/test-demo/src/pages/Home.tsx
- integration/app/test-demo/src/pages/VideoFilterTestApp.tsx
**Issue #:** 
Adds a integration test app for video filters. No integration tests have been added.
**Testing**
yes
Ran the test demo and switched between blur strengths.
N/a - integration test infra
> Add integration test app for video filter tests

- CHANGELOG.md
- src/components/sdk/DeviceSelection/CameraSelection/BackgroundBlurCheckbox.tsx
- src/components/sdk/DeviceSelection/CameraSelection/QualitySelection.tsx
- src/components/sdk/DeviceSelection/CameraSelection/index.tsx
- src/components/sdk/DeviceSelection/DeviceInput.tsx
- src/components/sdk/DeviceSelection/MicSelection/index.tsx
- src/components/sdk/DeviceSelection/SpeakerSelection/index.tsx
- src/components/sdk/MeetingControls/AudioInputControl.tsx
- src/components/sdk/MeetingControls/AudioInputVFControl.tsx
- src/components/sdk/MeetingControls/AudioOutputControl.tsx
- src/components/sdk/MeetingControls/ContentShareControl.tsx
- src/components/sdk/MeetingControls/VideoInputBackgroundBlurControl.tsx
- src/components/sdk/MeetingControls/VideoInputControl.tsx
- src/components/sdk/RosterAttendee/index.tsx
- src/components/stylingGuide.stories.mdx
- src/components/ui/Checkbox/index.tsx
- src/components/ui/Input/InputWrapper.tsx
- src/components/ui/Input/Styled.tsx
- src/components/ui/MicVolumeIndicator/Styled.tsx
- src/components/ui/Modal/ModalButtonGroup.tsx
- src/components/ui/Modal/Styled.ts
- src/components/ui/Select/Styled.tsx
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/712
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/196
Add a styling guide for the component library - this shows builders how to implement custom styling on all of our components.
This should publish a new documentation page on storybook for styling. Ran storybook to confirm that the docs show correctly. Here is a preview: https://github.com/aws/amazon-chime-sdk-component-library-react/blob/db863433b004299ef639ac6242ca7f77647101ab/src/components/stylingGuide.stories.mdx
**Testing**
yes
manually added each changed component in the integration test app and …
> Add custom styling capabilites to some components and add styling guide

- .github/script/get-pre-release-name.js
- .github/script/need-deploy-storybook.js
- .github/workflows/continuous-integration.yml
- .github/workflows/deploy.yml
- .github/workflows/publish.yml
- .github/workflows/roster-integration.yml
- .gitignore
- CHANGELOG.md
- package-lock.json
- package.json
- scripts/generate-version.js
- scripts/release.js
- scripts/update-sdk-version.js
- scripts/utilities.js
- scripts/version-utils.js
- src/versioning/Versioning.ts
Change to get version from git in `Versioning.ts` like in JS SDK.
Replace our current release script:
- Include new options for handling major and pre-build versions (beta).
- Include new option for redeploy demo in release or hotfix branch so that we could do incorporate fix and redeploy test demo without rerun the entire script.
- Change release to bump version at the beginning of any new version.
Also update our publish script to tag pre-release (beta) version.
**Testing:**
- Test the release script by manually executing.
*Can these tested using a demo application? Please provide reproducible step-by-step instructions.*
No
**Checklist:**
2. Do you add, modify, or delete public API definitions? …
> Add new release script

- .eslintrc.json
- CHANGELOG.md
- integration/app/test-demo/src/containers/MeetingForm.tsx
- jest.config.js
- src/components/introduction.stories.mdx
- src/components/migrationToV3.stories.mdx
- src/components/quickStarts.stories.mdx
- src/components/sdk/introduction.stories.mdx
- src/index.ts
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/MeetingProvider/index.tsx
- src/providers/MeetingProvider/types.ts
- src/providers/introduction.stories.mdx
- tsconfig.json
- tst/hooks/sdk/useActiveSpeakersState.test.tsx
- tst/providers/BackgroundBlurProvider/index.test.tsx
- tst/providers/MeetingProvider/MeetingManager.test.ts
- tst/providers/MeetingProvider/index.test.tsx
**Issue #724:** 
- Add `MeetingSessionConfiguration` as a required param to `MeetingManager` join method.
- Remove `MeetingSessionConfiguration` properties from `MeetingProvider` props.
**Testing**
Yes
By writing unit tests
Documentation changes will follow in a separate PR. Will link the other PR when ready.
> [V3] Add a new param meetingSessionConfiguration to meetingManager.join method

- src/components/migrationToV3.stories.mdx
- src/providers/MeetingProvider/MeetingManager.ts
- src/types/index.ts
- Remove `meetingRegion` from `MeetingManager` because we do not use that value anywhere in the library. Application can still get it from the `createMeeting` API response in aws-sdk.
- Fix some minor bugs that remove the `meetingStatus.Ended` as well as `DeviceLabels.None` check.
**Testing**
2. How did you test these changes? Manually test with latest meeting demo.
> Remove meetingRegion from MeetingManager

- CHANGELOG.md
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/index.tsx
**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/756
Remove logging of JSON.stringify to mitigate error thrown by JSON.stringify
**Testing**
> Remove log circular structure error for JSON.stringify

- scripts/release.js
**Issue #:** 
- In the dependency installation check for any warning or errors we install `react` without specifying the version.
- Since now 18.0.0 is released on `react` side, this script installed 18.0.0 for react which is not compatible with our library hence, install tagged 17.0.1 versions to solve this issue.
```
Install amazon-chime-sdk-component-library-react and amazon-chime-sdk-js sdk as dependencies, check if there is peer dependency warning for amazon-chime-sdk-component-library-react
Wrote to /Users/devalevd/MCM-56333256/dependency-check-app/package.json:
{
"name": "dependency-check-app",
"version": "1.0.0",
"description": "",
"main": "index.js",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"keywords": [],
"author": "",
"license": "ISC"
}
added 5 …
```
> Fix dependency installation check in release script

- CHANGELOG.md
- src/components/migrationToV2.stories.mdx
- src/components/migrationToV3.stories.mdx
**Issue #:** 
* Fix command line sample to install v2, v3 dependencies in migration guide
**Testing**
Yes
N/A
N/A
> Fix npm install command line in migration guide

- CHANGELOG.md
- src/components/introduction.stories.mdx
- src/components/migrationToV2.stories.mdx
- src/components/migrationToV3.stories.mdx
- src/components/quickStarts.stories.mdx
- src/components/sdk/RemoteVideo/RemoteVideo.stories.mdx
- src/components/stylingGuide.stories.mdx
- src/components/ui/VideoGrid/VideoGrid.mdx
- src/hooks/sdk/docs/useActiveSpeakersState.stories.mdx
- src/hooks/sdk/docs/useDeviceLabelTriggerStatus.stories.mdx
- src/providers/AudioVideoProvider/docs/AudioVideoProvider.stories.mdx
- src/providers/AudioVideoProvider/docs/useAudioVideo.stories.mdx
- src/providers/BackgroundBlurProvider/docs/BackgroundBlurProvider.stories.mdx
- src/providers/BackgroundBlurProvider/docs/useBackgroundBlur.stories.mdx
- src/providers/BackgroundReplacementProvider/docs/BackgroundReplacementProvider.stories.mdx
- src/providers/BackgroundReplacementProvider/docs/useBackgroundReplacement.stories.mdx
- src/providers/DevicesProvider/docs/AudioOutputProvider.stories.mdx
- src/providers/DevicesProvider/docs/useAudioOutputs.stories.mdx
- src/providers/LoggerProvider/docs/LoggerProvider.stories.mdx
- src/providers/MeetingEventProvider/docs/MeetingEventProvider.stories.mdx
- src/providers/MeetingEventProvider/docs/useMeetingEvent.stories.mdx
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/VoiceFocusProvider/docs/VoiceFocusProvider.stories.mdx
- src/providers/introduction.stories.mdx
**Issue #:** 
HTTP URLs in storybook are parsed incorrectly due to this [storybook issue](https://github.com/storybookjs/storybook/issues/9005)
For example:
```
[client application](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting/src)
```
is parsed to `https://aws.github.io/https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting/src`.
* Replace all absolute markdown links with `<a>` tag.
* Improve device permission handling guide to make it more clear.
**Testing**
Yes.
Run storybook locally and verify it works as expected.
N/A …
> Fix broken URLs and improve device permission guide

- CHANGELOG.md
- src/providers/LocalVideoProvider/docs/LocalVideoProvider.stories.mdx
- src/providers/LocalVideoProvider/docs/useLocalVideo.stories.mdx
**Issue #:** 
* Clean up the wrong statement of preview video state and local video state in stories of `LocalVideoProvider` and `useLocalVideo`.
**Testing**
Yes
Run storybook locally and verify it works.
N/A
> Clean up the wrong statement in stories of LocalVideoProvider and useLocalVideo

- .github/workflows/roster-integration.yml
- CHANGELOG.md
- integration/app/test-demo/package-lock.json
- integration/app/test-demo/package.json
- integration/app/test-demo/src/pages/VideoFilterTestApp.tsx
- integration/app/test-demo/webpack.config.js
- integration/package-lock.json
- integration/package.json
- integration/script/run-test
**Issue #:** 
* Update integration test demo to install `amazon-chime-sdk-component-library-react` from local instead of from npm.
* Update corresponding GitHub Action and scripts.
* Update `VideoFilterTestApp` to adapt to V3 changes.
* Update `webpack.config` for test demo to solve conflict dependencies issue. Check [here](https://github.com/facebook/react/issues/13991#issuecomment-435587809) for more details.
**Testing**
Yes
* Test run-script locally and confirm it works.
* Run test demo locally and confirm the script and demo works as expected.
* Test GitHub Action through this PR and confirm it works.
3. If you made changes to the component library, have you …
> Install React SDK for test demo from local instead of npm

- CHANGELOG.md
- src/components/introduction.stories.mdx
- src/components/migrationToV2.stories.mdx
- src/components/migrationToV3.stories.mdx
- src/components/quickStarts.stories.mdx
- src/components/sdk/RemoteVideo/RemoteVideo.stories.mdx
- src/components/stylingGuide.stories.mdx
- src/hooks/sdk/docs/useActiveSpeakersState.stories.mdx
- src/hooks/sdk/docs/useDeviceLabelTriggerStatus.stories.mdx
- src/providers/AudioVideoProvider/docs/AudioVideoProvider.stories.mdx
- src/providers/AudioVideoProvider/docs/useAudioVideo.stories.mdx
- src/providers/BackgroundBlurProvider/docs/BackgroundBlurProvider.stories.mdx
- src/providers/BackgroundBlurProvider/docs/useBackgroundBlur.stories.mdx
- src/providers/BackgroundReplacementProvider/docs/BackgroundReplacementProvider.stories.mdx
- src/providers/BackgroundReplacementProvider/docs/useBackgroundReplacement.stories.mdx
- src/providers/DevicesProvider/docs/AudioOutputProvider.stories.mdx
- src/providers/DevicesProvider/docs/useAudioOutputs.stories.mdx
- src/providers/LocalVideoProvider/docs/LocalVideoProvider.stories.mdx
- src/providers/LocalVideoProvider/docs/useLocalVideo.stories.mdx
- src/providers/LoggerProvider/docs/LoggerProvider.stories.mdx
- src/providers/MeetingEventProvider/docs/MeetingEventProvider.stories.mdx
- src/providers/MeetingEventProvider/docs/useMeetingEvent.stories.mdx
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
- src/providers/VoiceFocusProvider/docs/VoiceFocusProvider.stories.mdx
- src/providers/introduction.stories.mdx
**Issue #:** 
* Revert changes in `5605a007c98059758d5f3fb5d719ddc84aeeabbb`.
* Fix several typos.
**Testing**
Yes
Run storybook locally and confirm it works as expected.
N/A
> Revert change to replace markdown links with HTML <a> tag

- integration/README.md
- integration/package-lock.json
- integration/package.json
**Issue #:** 
1. Add warning for unnamed saucelabs usage in the readme of integration test
2. Bump up the `chromedriver` to latest verison to support Chrome 101.
**Testing**
Yes
N/A
N/A
> Add warning for unnamed saucelabs tunnel and bump up chromedriver

- package-lock.json
- package.json
**Issue #:** 
To fix security alerts in [meeting demo sample](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting), we have to first upgrade the JS SDK in this repo and then `npm install` should update the component library submodule in the meeting demo, otherwise we run into below errors when you will run `npm run start`:
```
[0] ERROR in /Volumes/workplace/aws-samples/amazon-chime-sdk/apps/meeting/src/containers/MeetingForm/index.tsx
[0] ./src/containers/MeetingForm/index.tsx 122:32-59
[0] [tsl] ERROR in /Volumes/workplace/aws-samples/amazon-chime-sdk/apps/meeting/src/containers/MeetingForm/index.tsx(122,33)
[0]       TS2345: Argument of type 'import("/Volumes/workplace/aws-samples/amazon-chime-sdk/apps/meeting/node_modules/amazon-chime-sdk-js/build/meetingsession/Meet …
```
> Upgrade JS SDK to latest NPM 3.6.0

- CHANGELOG.md
- src/providers/ContentShareProvider/docs/useContentShareControls.stories.mdx
- src/providers/ContentShareProvider/index.tsx
- src/types/index.ts
**Issue #:**  None. Though technically addresses https://github.com/aws/amazon-chime-sdk-component-library-react/issues/313  .
**Description of changes:**  Continuation of https://github.com/aws/amazon-chime-sdk-js/pull/2467 . This exposes the ability to pass specific `MediaStream` to `toggleContentShare` to address use cases like file share, or transformed content share.
**Testing**
y
I hacked in a change similar to that in storybook into the meeting demo and confirmed it works as expected.
I think so?
By submitting this pull request, I confirm that my contribution is made under the terms …
> Expose ability to pass specific MediaStream to toggleContentShare

- .gitignore
- scripts/release.js
**Issue #:** 
Our release script didn't remove react sdk tarball after installing it when deploying the demo. So when raising version bump PR, the tarball is included in the commit.
* Simply run `rm -rf <path_to_tarball>` after installing tarball.
* Add `*.tgz` to `.gitignore`.
**Testing**
N/A, just script change.
Test the release script and confirm the tarball is deleted.
N/A
> Remove tarball after installing it in demo

- CHANGELOG.md
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/index.tsx
**Issue #:** 
Add an observer prop to the BG Blur and Replacement provider  to add and remove the observer to the initialized processor on mount/umount.
**Testing**
yes
Add a prop to the Background Blur Provider in the meeting demo and confirm that observer functions are executed. (Just console log when the events fired)
4. If you made changes to the component library, have you provided corresponding documentation changes?
Yes
> Add observer prop to the BG Blur and Replacement Provider

- CHANGELOG.md
- src/providers/BackgroundBlurProvider/docs/BackgroundBlurProvider.stories.mdx
- src/providers/BackgroundBlurProvider/docs/useBackgroundBlur.stories.mdx
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/docs/BackgroundReplacementProvider.stories.mdx
- src/providers/BackgroundReplacementProvider/docs/useBackgroundReplacement.stories.mdx
- src/providers/BackgroundReplacementProvider/index.tsx
**Issue #:** 
Revert the changes to expose an observer prop on BG Blur provider and BG Replacement provider. Instead, expose the processors that are created in the BG Blur and BG Replacement providers, so that builders may modify the processors, or add observer functions directly to the processors.
**Testing**
yes
In the test demo, take the processor from the BG Blur and BG replacement providers, and call addObserver() and removeObserver() on them.
4. If you made changes to the component library, have you provided corresponding documentation changes?
yes
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Bg blur observer

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/sdk/MeetingControls/AudioInputVFControl.tsx
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/index.tsx
- src/providers/VoiceFocusProvider/docs/VoiceFocusProvider.stories.mdx
- src/providers/VoiceFocusProvider/index.tsx
- tst/providers/BackgroundBlurProvider/index.test.tsx
**Issue #:** 
Related to: https://github.com/aws/amazon-chime-sdk-js/pull/2526
1. Need to stop the voice focus transformer on unmount to prevent memory leak. BG Blur and BG Replacement do the same already.
2. Stop initializing a BG Blur and BG Replacement on mount. It's not being used anyways. 
**Testing**
Yes
In the meeting demo, join a meeting with Web Audio enabled. Then, leave the meeting. 
Then, open the Task Manager for Chrome and see that the chrome tab that is running the meeting demo has one dedicated worker. Then, disable Web Audio checkbox. Verify that the worker thread has been killed.
3. If you made changes to the component library, have you provided …
> Destroy the VoiceFocus transformer on unmount of VoiceFocusProvider

- CHANGELOG.md
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/index.tsx
- tst/providers/BackgroundBlurProvider/index.test.tsx
**Issue #:** 
Need to revert the changes from the previous commit - I removed this unnecessary initalizing of the Background blur and Background replacement on the mounting of the provider, but it turns out that we need to call `initializeBackgroundBlur`  or `initializeBackgroundReplacement` in order to initialize the `isBackgroundBlurSupported` or `isBackgroundReplacementSupported` state of the corresponding providers. Otherwise, this could be a breaking change, as the initial value of the `isBackgroundBlurSupported` or `isBackgroundReplacementSupported` for the providers will always be false, when in reality it should be true.
**Testing**
yes
Tested on the react …
> Revert changes to Background Blur and Background Replacement to fix bug

- CHANGELOG.md
- integration/utils/config.js
- src/hooks/sdk/docs/useMeetingStatus.stories.mdx
- src/providers/MeetingProvider/MeetingManager.ts
- src/types/index.ts
**Issue #:** 
NA
- `audioVideoDidStartConnecting` helps in listening to whether JS SDK is reconnecting.
- Applications depending on Chime SDK component library currently do not have a out of the box `MeetingStatus` to tell whether the JS SDK is in reconnection. Thus, add `audioVideoDidStartConnecting` with a new `MeetingStatus.Reconnecting` to aid such a use case.
- Fix: Publish `MeetingStatus.Failed` only when a non-terminal failure is encountered. Currently, some statuses pass both the `sessionStatus.isFailure()` as well as `sessionStatus.isTerminal()` in JS SDK, thus, for a status if it is in both, then it will be considered as failure and `MeetingStatus.TerminalFailure` will never get set. Check below file for more information on both methods in JS SDK: …
> Add `MeetingStatus.Reconnecting` and `audioVideoDidStartConnecting` observer

- CHANGELOG.md
- integration/utils/config.js
- src/providers/MeetingProvider/MeetingManager.ts
- src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
- src/providers/MeetingProvider/types.ts
**Issue #:** 
- Skip listing and selecting devices as part join method call
- Add `skipDeviceSelection` flag to meetingManager.join API options
- Add corresponding documentation update.
**Testing**
Yes
I created a new component to test in the demo and tested both ways enabling and disabling the `skipDeviceSelection` flag and verified that the devices were correctly selected + the attendee appeared in the roster. I tested in Firefox. The PR for that will be raised once this change merges in.
Yes
By submitting this pull request, I confirm that my contribution is …
> Skip listing and selecting devices as part joinmethod call

- scripts/release.js
**Issue #:** 
N/A
- Update the NPM release script for React 18 support and mitigate the styled-components build error
**Testing**
I can't run the command as this PR modifies the release script itself. 
Not testable
N/A
> Update the release script for React 18 support

- README.md
**Issue #:** 
#900 
README update to mention `npm run build` first and then `npm start` so that storybook builds successfully.
**Testing**
1. Have you successfully run `npm run build:release` locally? NA just README update.
2. How did you test these changes? Locally previewing in the VS code.
3. If you made changes to the component library, have you provided corresponding documentation changes? NA
> Update README to mention build first and then start the storybook

- src/providers/ContentShareProvider/index.tsx
- tst/providers/ContentShareProvider/index.test.tsx
**Issue #:** 
Currently in `toggleContentShare` we do not await for the JS SDK API thus, if the APIs fail, callers would not be able to handle it.
**Testing**
Yes
Add unit tests
> Add await for toggleContentShare

- CHANGELOG.md
- src/providers/BackgroundReplacementProvider/docs/BackgroundReplacementProvider.mdx
- src/providers/BackgroundReplacementProvider/docs/useBackgroundReplacement.mdx
**Issue #:** 
Update storybook to add `changeBackgroundReplacementImage`.
**Testing**
Yes
N/A
Yes
> Update storybook to add changeBackgroundReplacementImage

- CHANGELOG.md
- src/providers/BackgroundReplacementProvider/docs/BackgroundReplacementProvider.mdx
- src/providers/BackgroundReplacementProvider/docs/useBackgroundReplacement.mdx
**Issue #:** 
* Add usage of `changeBackgroundReplacementImage` in storybook.
**Testing**
Yes
N/A
Yes.
> Add usage of changeBackgroundReplacementImage in storybook

- CHANGELOG.md
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/index.tsx
**Issue #:** 
Default to logger from logger provider when initiate bgBlur, bgReplacement processors
**Testing**
2. How did you test these changes? Test using react meeting demo
3. If you made changes to the component library, have you provided corresponding documentation changes? 
> Use pass in logger for ml modules

- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/index.tsx
**Issue #: remove stringify bg blur/replacement processor object. 
**Testing**
Yes
Locally and deployed to CF.
5. If you made changes to the component library, have you provided corresponding documentation changes?
> Remove logging processor object for BG

- CHANGELOG.md
- package-lock.json
- package.json
- scripts/release.js
This reverts commit 2eb6e5dfbcaa1e159c7b9ca42cea424625f243eb.
**Issue #:**  Cancel the version bump.
**Testing**
> Revert "Version bump for amazon-chime-sdk-component-library-react@3.11.0 (#980)

- CHANGELOG.md
- src/providers/BackgroundBlurProvider/index.tsx
- src/providers/BackgroundReplacementProvider/index.tsx
- tst/providers/BackgroundBlurProvider/index.test.tsx
**Issue #:** 
1. Fix the conditions where `BackgroundReplacementProvider` needs to be re-rendered. Remove the image size comparison because now it supports dynamically change replacement image in an active processor. The processor recreation when image changes will cost to fetch assets again.
2. Avoid to log the entire `options` props in `BackgroundReplacementProvider`, the optional `logger` prop could potentially be nested JSON.
**Testing**
Yes
4. Locally and private build tested by QA
5. If you made changes to the component library, have you provided corresponding documentation changes?
By submitting this pull request, I confirm that my contribution is made under …
> Fix conditions where BackgroundReplacementProvider needs to be re-rendered, Fix to not log the entire options object

- CHANGELOG.md
- src/components/sdk/ContentShare/ContentShare.mdx
- src/components/sdk/ContentShare/index.tsx
- src/components/sdk/FeaturedRemoteVideos/index.tsx
- src/components/sdk/VideoTileGrid/VideoTileGrid.mdx
- src/components/sdk/VideoTileGrid/index.tsx
- src/providers/ContentShareProvider/docs/ContentShareProvider.mdx
- src/providers/ContentShareProvider/docs/useContentShareControls.mdx
- src/providers/ContentShareProvider/docs/useContentShareState.mdx
- src/providers/ContentShareProvider/index.tsx
- src/providers/ContentShareProvider/state.tsx
- src/providers/MeetingProvider/index.tsx
- src/providers/RemoteVideoTileProvider/state.tsx
- src/types/index.ts
**Issue #:** 
- Added support for multiple content shares in meetings through the `ContentShareProvider`. The provider now accepts a `maxContentShares` prop (default: 1, range 1-2) to specify the maximum number of concurrent content shares allowed.
- Added new collections in `ContentShareState` to track multiple content shares: `tiles`, `tileIdToAttendeeId`, and `attendeeIdToTileId`.
- Added optional `tileId` prop to the `ContentShare` component to specify which content share to render.
- Added `canStartContentShare` state to control when content sharing is allowed based on the current number of shares and configured maximum.
- Maintained backward compatibility by keeping `tileId` and `sharingAttendeeId` properties, which now point to the most recently started …
> Add support for multiple content shares
