aws/amazon-chime-sdk-component-library-react

.github/workflows/continuous-integration.yml
.github/workflows/send-pull-request-notification.yml
.github/workflows/send-webhook-star-notification.yml
scripts/prebuild.js
scripts/release.js
scripts/verdaccio.js

**Issue #:** 
- Only changes to ./src will require a changelog
- Only changes to ./src will require snapshot testing
**Testing**
- The github actions are tested when I submit this PR
- not required for these changes
- n/a

Add conditional checks for requiring Changelog and Snapshot testing

---

CHANGELOG.md
README.md
src/components/introduction.stories.mdx
src/components/sdk/ContentShare/ContentShare.stories.mdx
src/components/sdk/DeviceSelection/CameraSelection/index.tsx
src/components/sdk/DeviceSelection/MicSelection/index.tsx
src/components/sdk/DeviceSelection/SpeakerSelection/index.tsx
src/components/sdk/DeviceSelection/docs/CameraSelection.stories.mdx
src/components/sdk/DeviceSelection/docs/MicSelection.stories.mdx
src/components/sdk/DeviceSelection/docs/QualitySelection.stories.mdx
src/components/sdk/DeviceSelection/docs/SpeakerSelection.stories.mdx
src/components/sdk/FeaturedRemoteVideos/FeaturedRemoteVideos.stories.mdx
src/components/sdk/LocalVideo/LocalVideo.stories.mdx
src/components/sdk/MeetingControls/AudioInputControl.tsx
src/components/sdk/MeetingControls/AudioOutputControl.tsx
src/components/sdk/MeetingControls/ContentShareControl.tsx
src/components/sdk/MeetingControls/VideoInputControl.tsx
src/components/sdk/MeetingControls/docs/AudioInputControl.stories.mdx
src/components/sdk/MeetingControls/docs/AudioOutputControl.stories.mdx
src/components/sdk/MeetingControls/docs/ContentShareControl.stories.mdx
src/components/sdk/MeetingControls/docs/VideoInputControl.stories.mdx
src/components/sdk/MicrophoneActivity/MicrophoneActivity.stories.mdx
src/components/sdk/PreviewVideo/PreviewVideo.stories.mdx
src/components/sdk/RemoteVideo/RemoteVideo.stories.mdx
src/components/sdk/RemoteVideos/RemoteVideos.stories.mdx
src/components/sdk/RosterAttendee/RosterAttendee.stories.mdx
src/components/sdk/RosterAttendee/index.tsx
src/components/sdk/VideoTileGrid/VideoTileGrid.stories.mdx
src/components/sdk/introduction.stories.mdx

* Improve docs of SDK components & add Github documentation link to README
**Testing**
2. How did you test these changes? verified in SB

Improve docs of SDK components & add Github documentation link to README

---

.github/pull_request_template.md
.github/workflows/continuous-integration.yml

**Issue #:** 
Updates the PR Template to ask if documentation has been included.
Also updates the github action that checks if the changes are within src folder
**Testing**
n/a
n/a

Add question about including documentation in PR template

---

.github/workflows/continuous-integration.yml
.github/workflows/send-pull-request-notification.yml
scripts/prebuild.js

**Issue #:** 
test
**Testing**
no
by submitting this Pr
n/a

Test github workflow

---

CHANGELOG.md
src/components/ui/Badge/Badge.mdx
src/components/ui/Button/Button.mdx
src/components/ui/Checkbox/Checkbox.mdx
src/components/ui/ContentTile/ContentTile.mdx
src/components/ui/ControlBar/ControlBar.mdx
src/components/ui/Flex/Flex.mdx
src/components/ui/FormField/FormField.mdx
src/components/ui/Grid/Grid.mdx
src/components/ui/Heading/Heading.mdx
src/components/ui/Input/Input.mdx
src/components/ui/Label/Label.mdx
src/components/ui/Modal/Modal.mdx
src/components/ui/Navbar/Navbar.mdx
src/components/ui/Notification/Notification.mdx
src/components/ui/PopOver/PopOver.mdx
src/components/ui/Radio/Radio.mdx
src/components/ui/RadioGroup/RadioGroup.mdx
src/components/ui/Roster/Roster.mdx
src/components/ui/Select/Select.mdx
src/components/ui/Textarea/Textarea.mdx
src/components/ui/VideoGrid/VideoGrid.mdx
src/components/ui/VideoTile/VideoTile.mdx

**Issue #:** 
Docs were missing some global styles that were causing inaccurate rendering
Adds GlobalStyles to each of our docs components
**Testing**

Fix storybook docs rendering

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
Publish 1.1.0 to NPM
**Testing**

Publish amazon-chime-sdk-component-library-react@1.1.0

---

CHANGELOG.md
demo/meeting/server.js
demo/meeting/src/app.tsx
demo/meeting/src/containers/MeetingDetails/index.tsx
demo/meeting/src/containers/MeetingForm/RegionSelection.tsx
demo/meeting/src/containers/MeetingForm/index.tsx
demo/meeting/src/meetingConfig.ts
demo/meeting/src/providers/AppStateProvider.tsx
demo/meeting/src/utils/api.ts
src/providers/MeetingProvider/MeetingManager.ts
src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
src/providers/MeetingProvider/index.tsx
src/providers/MeetingProvider/types.ts

- Add automatic region detection in demo meeting form
- Add PostLogger support in MeetingProvider
**Testing**
manually
Added docs for logger

Add region detection, postLogger support in MeetingProvider

---

CHANGELOG.md
package-lock.json

**Issue #:** 
Move recent changelogs to Unreleased
**Testing**
Yes
n/a
n/a

Move changelogs to Unreleased

---

CHANGELOG.md
src/hooks/useElementAspectRatio/index.tsx
src/index.ts

**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/171
Add some 
**Testing**
yes
n/a
yes

Add missing exports to index.ts

---

src/components/sdk/VideoTileGrid/VideoTileGrid.stories.mdx

**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/163
Update some documentation
**Testing**
Yes

Add clarification around video tile grid documentation

---

CHANGELOG.md
src/providers/MeetingProvider/MeetingManager.ts

**Issue #:** 
Some incorrect logic in the device label trigger setup caused wrong permission states
Fix permission trigger state by updating in the trigger function
**Testing**
manually

Fix incorrect device permission status

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
Release 1.2.0
**Testing**

Publish amazon-chime-sdk-component-library-react@1.2.0

---

CHANGELOG.md
src/components/sdk/ContentShare/ContentShare.stories.mdx
src/components/sdk/ContentShare/index.tsx
src/components/sdk/MeetingControls/ContentShareControl.tsx
src/components/sdk/MeetingControls/docs/ContentShareControl.stories.mdx
src/components/ui/ContentTile/index.tsx
src/components/ui/Input/FileInput.tsx
src/components/ui/Input/Styled.tsx
src/components/ui/PopOver/index.tsx
src/providers/ContentShareProvider/docs/ContentShareProvider.stories.mdx
src/providers/ContentShareProvider/docs/useContentShareControls.stories.mdx
src/providers/ContentShareProvider/docs/useContentShareState.stories.mdx
src/providers/ContentShareProvider/index.tsx
src/providers/ContentShareProvider/state.tsx
src/types/index.ts

* Add share video file feature and update documentation accordingly
**Testing**
2. How did you test these changes? npm start test && npm run test:snapshots && visually check documentations.

Add share video file feature and update documentation accordingly

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@1.3.0

---

CHANGELOG.md
src/components/ui/Chat/ChannelList/Styled.tsx

Adding missing base styles to ChannelList component
**Testing**
Yes
Storybook
n/a

Add base styles to ChannelList

---

CHANGELOG.md
src/components/ui/Chat/InfiniteList/index.tsx

**Issue #:** 
Fix build error in InfiniteList component
**Testing**
yes
Built storybook and demo app
n/a

Fix TS error in InfiniteList

---

CHANGELOG.md
src/components/ui/Roster/RosterCell/index.tsx

**Issue #:** 
Added space for extraIcons in RosterCell, Moved menu to be able show when "running late"
**Testing**
2. How did you test these changes? tested in other repro

Added space for extraIcons in RosterCell, Moved menu to be able show when "running late"

---

demo/meeting/package-lock.json
demo/meeting/package.json
src/components/sdk/Base/index.tsx
src/components/sdk/RosterAttendee/index.tsx
src/components/ui/Base/index.ts
src/components/ui/Navbar/NavbarHeader.tsx
src/components/ui/Navbar/NavbarItem.tsx
src/components/ui/Navbar/index.tsx
src/components/ui/PopOver/PopOver.mdx
src/components/ui/PopOver/index.tsx
src/components/ui/Roster/PopOverMenu.tsx
src/components/ui/Roster/Roster.stories.tsx
src/components/ui/Roster/RosterCell/index.tsx
src/components/ui/Roster/RosterGroup.tsx
src/components/ui/Roster/RosterHeader.tsx
src/components/ui/Roster/index.tsx
tst/components/ui/PopOver/index.test.tsx

**Issue #:** 
Work in progress PR, just posting to get feedback and for client team visibility
Will update this PR to address issue #252, #253
Roster was rendering some broken HTML. Updating Popover to accept an alternate prop so you can control the full button rendering
**Testing**
2. How did you test these changes? unit, manually in demo

Fix roster button accessibility bug

---

CHANGELOG.md
src/components/ui/PopOver/PopOverHeader.tsx

(allows for multiline support)
**Testing**
2. How did you test these changes? tested in another repo

Added passthrough for a react node in the subtitle of PopOverHeader

---

src/components/ui/icons/All/All.stories.tsx
src/components/ui/icons/Lock/Lock.mdx
src/components/ui/icons/Lock/Lock.stories.tsx
src/components/ui/icons/Lock/index.tsx
src/components/ui/icons/index.tsx

**Issue #:** 
Add Lock Icon
Add Lock Icon for Badge usage later
**Testing**
Yes
Run `npm start` and see the storybook on http://localhost:9009/?path=/story/ui-components-icons-lock--lock
Yes. Add corresponding story

Add Lock icon

---

src/components/sdk/FeaturedRemoteVideos/index.tsx
src/components/sdk/RemoteVideos/index.tsx

Add some explicit "any" type info to help with consuming this in the client
**Testing**
Yes.
N/A
N/A

Add some explicit "any" type info to help with consuming this in the client

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
Publish 1.4.0.
**Testing**

Publish amazon-chime-sdk-component-library-react@1.4.0

---

src/components/ui/Badge/Badge.mdx
src/components/ui/Badge/Badge.stories.tsx
src/components/ui/Badge/Styled.tsx
src/components/ui/Badge/index.tsx

**Issue #:** 
We need to loose up Badge value prop to let it accept `number|string|JSX.Element`
**Testing**
Yes
In the storybook
Yes. The storybook is updated

Update Badge component to loose up value prop

---

CHANGELOG.md
src/index.ts

I forgot to export these
**Testing**

Also export utilities and ChannelItem

---

CHANGELOG.md

**Issue #:** 
See title
**Testing**
No, no change to source code

Move unreleased changes to unreleased section of changelog

---

CHANGELOG.md
src/components/ui/Chat/ChatBubble/ChatBubbleContainer.tsx

Clean up unused import in ChatBubble component

---

package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@1.5.0

---

CHANGELOG.md
src/components/ui/icons/All/All.stories.tsx
src/components/ui/icons/ConnectionProblem/ConnectionProblem.mdx
src/components/ui/icons/ConnectionProblem/ConnectionProblem.stories.tsx
src/components/ui/icons/ConnectionProblem/index.tsx
src/components/ui/icons/index.tsx

**Issue #:** 
N/A
Adding a connection problem icon
**Testing**
Yes.
Locally via storybook
Yes

Add ConnectionProblem icon

---

demo/chat/README.md

Update Chat Demo Readme

---

demo/chat/src/backend/serverless/template.yaml

Added missing Chime user actions policies in CloudFormation template.
**Testing**

Update CFT template policy

---

package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@1.6.0

---

CHANGELOG.md
README.md

**Issue #:** 
**Description of changes:** Update README with solutions of common issues
**Testing**
2. How did you test these changes? NA
3. If you made changes to the component library, have you provided corresponding documentation changes? NA

[Documentation] Update README with solutions of common issues

---

CHANGELOG.md
src/providers/ContentShareProvider/docs/ContentShareProvider.stories.mdx
src/providers/ContentShareProvider/docs/useContentShareControls.stories.mdx
src/providers/ContentShareProvider/docs/useContentShareState.stories.mdx

**Issue #:**  [#318](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/318)
**Testing**
1. Have you successfully run `npm run build:release` locally? YES
2. How did you test these changes? run storybook and verify
3. If you made changes to the component library, have you provided corresponding documentation changes? NA

Update ContentShare docs(#318)

---

CHANGELOG.md
src/components/ui/Textarea/index.tsx

**Issue #:** 
Add forwardRef for Textarea
**Testing**
Yes
Tested manually
Yes

Add forwardRef for Textarea

---

CHANGELOG.md
src/components/ui/icons/All/All.stories.tsx
src/components/ui/icons/ZoomIn/ZoomIn.mdx
src/components/ui/icons/ZoomIn/ZoomIn.stories.tsx
src/components/ui/icons/ZoomIn/index.tsx
src/components/ui/icons/ZoomOut/ZoomOut.mdx
src/components/ui/icons/ZoomOut/ZoomOut.stories.tsx
src/components/ui/icons/ZoomOut/index.tsx
src/components/ui/icons/index.tsx

**Issue #:** 
Added ZoomIn and ZoomOut icons
**Testing**
2. How did you test these changes? with storybook

Added ZoomIn and ZoomOut icons

---

CHANGELOG.md
src/components/ui/icons/ZoomIn/index.tsx
src/components/ui/icons/ZoomOut/index.tsx

**Issue #:** 
Fix incorrect fill-rule property
**Testing**
2. How did you test these changes? manually in storybook

Fix incorrect fill-rule property

---

CHANGELOG.md
package-lock.json
src/components/ui/Button/Button.stories.tsx
src/components/ui/Button/IconButton.tsx
src/components/ui/Button/Styled.tsx
src/components/ui/ControlBar/Styled.tsx
src/components/ui/Modal/ModalHeader.tsx
src/components/ui/Navbar/Navbar.stories.tsx
src/components/ui/Navbar/NavbarHeader.tsx
src/components/ui/Navbar/NavbarItem.tsx
src/components/ui/Navbar/Styled.tsx
src/components/ui/Navbar/index.tsx
src/components/ui/icons/Svg.tsx
tst/components/ui/Button/IconButton.test.tsx
tst/components/ui/Navbar/NavbarItem.test.tsx

Re-implementing this PR as a previous merge resulted in an issue. 

refactor NavBar

---

demo/chat/src/containers/messages/Messages.jsx

**Issue #:** 
Updating the usage of `ChatBubble` for the new prop interface. Also fixed a small capitalization bug. 
**Testing**
yes
locally ran the demo app
n/a

Update ChatBubble implementation to 2.0 component design

---

demo/chat/package-lock.json
demo/chat/package.json

Update axios dependency in chat demo to 0.21.1 according to GitHub dependabot alert.
**Testing**
No since this is just for the chat demo.
Run npm install and npm start successfully 
No

Update axios dependency in chat demo

---

CHANGELOG.md
demo/chat/package-lock.json
demo/chat/package.json
demo/meeting/serverless/deploy.js
demo/meeting/src/utils/VersionLabel.tsx
package-lock.json
src/components/sdk/MeetingControls/AudioOutputControl.tsx
src/components/ui/icons/Caution/Caution.stories.tsx
src/components/ui/icons/Caution/index.tsx
src/components/ui/icons/Caution/styled.tsx
src/hooks/sdk/useSelectAudioOutputDevice.tsx
src/providers/DevicesProvider/AudioInputProvider.tsx
src/providers/LocalAudioOutputProvider/index.tsx
src/providers/MeetingProvider/MeetingManager.ts
src/utils/device-utils.ts

**Issue #:** 
Merging master into express branch
**Testing**
Yes
local build
n/a

Merge master into express

---

README.md
src/components/migrationToV2.stories.mdx

**Issue #:** 
Add V2 migration documentation to storybook.
**Testing**
Yes
Docs only
yes
yes

Add migration doc to storybook for V2

---

src/components/sdk/LocalVideo/LocalVideo.stories.mdx

fix LocalVideo story import

---

demo/chat/src/backend/serverless/template.yaml
demo/chat/src/containers/channels/ChannelsWrapper.jsx
demo/chat/src/providers/ChatMessagesProvider/index.jsx
demo/chat/src/services/AttachmentService.js
demo/chat/src/services/MessagingService.js
demo/chat/src/views/Channels/style.css
demo/chat/src/views/Signin/index.jsx

Fix spellings thru-out chat demo.
**Testing**

Fix misspelled

---

.gitignore
CHANGELOG.md
demo/chat/README.md
demo/chat/package-lock.json
demo/chat/package.json
demo/chat/webpack.config.js
demo/meeting/README.MD
demo/meeting/package-lock.json
demo/meeting/package.json
demo/meeting/webpack.config.js
package-lock.json
package.json
src/components/migrationToV2.stories.mdx

- Specify amazon-chime-sdk-js in the component library package.json dependencies.
**Testing**
2. How did you test these changes? Manually run build and the two meeting demo

Set amazon-chime-sdk-js in package.json dependency

---

package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
2.0 bump
**Testing**

Publish amazon-chime-sdk-component-library-react@2.0.0

---

src/components/ui/Navbar/NavbarItem.tsx

**Issue #:** 
Replacement for PR #411 
**Testing**

Navbaritem testid

---

package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
publish patch 2.0.1
**Testing**

Publish amazon-chime-sdk-component-library-react@2.0.1

---

.github/CODEOWNERS
.github/workflows/deploy.yml
demo/meeting/serverless/deploy.js
scripts/github-action-awscli-installation
scripts/release.js

**Issue #:** 
Add a deploy script to deploy our demo app every time we push to master branch. 
**Testing**
2. How did you test these changes? Verified that the github action deploys the demo correctly.

Add demo deploy workflow for components demo

---

CHANGELOG.md

**Issue #:** 
NA
- Fix the CHANGELOG order.
**Testing**
2. How did you test these changes? Just changelog update.

Correct the CHANGELOG order

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
None.
Publish amazon-chime-sdk-component-library-react@2.1.0
**Testing**
2. How did you test these changes? Locally.

Publish amazon-chime-sdk-component-library-react@2.1.0

---

src/components/ui/PopOver/PopOverItem.tsx

**Issue #:** 
add testId for PopOverItem
**Testing**
Yes
ran release script locally
yes

add testId for PopOverItem

---

CHANGELOG.md
src/components/ui/PopOver/index.tsx

**Issue #:** 
Add button click callback to PopOver.
**Testing**
Yes
Yes. Ran release script locally and manual test

Add button click callback to PopOver

---

README.md

**Issue #:** 
<No Issue> 
Improving README.md by fixing typo and adding additional resourcing details.
**Testing**
No
Preview via Github
Not applicable

Improving the README.md with overview and other resources

---

scripts/release.js

Add hotfix option for release script
**Testing**
2. How did you test these changes? Manually execute the script

Add hotfix option to release script

---

src/components/ui/Radio/index.tsx
src/components/ui/RadioGroup/index.tsx

**Issue #:** 
add testId to RadioGroup and Radio for client automation
**Testing**
Yes
ran release script locally
Yes

add testId to RadioGroup and Radio

---

CHANGELOG.md
README.md

**Issue #:** 
* Modify README to align with the latest code change #450 
* Add ChangeLog for housekeeping pr #442 (include changelog for bumping the react version)
* Add missing space and backticks for ChangeLog.
**Testing**
2. How did you test these changes? Manually test

Update README to aligh with change #450 and update ChangeLog for housekeeping pr #442

---

CHANGELOG.md
demo/chat/package-lock.json
demo/chat/package.json
demo/meeting/package-lock.json
demo/meeting/package.json
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
publish version to 2.2.0
**Testing**
2. How did you test these changes? Test demo app

Publish amazon-chime-sdk-component-library-react@2.2.0

---

CHANGELOG.md
scripts/release.js
scripts/utilities.js

**Issue #:** 
Add a step in release script to create a test react app, install latest version of component app as dependency and build the test app.
**Testing**
2. How did you test these changes? Manually run the release script with the code change snippet.

Add a step in release script to create a test react app for dependency check

---

CHANGELOG.md
demo/chat/package-lock.json
demo/chat/package.json
demo/meeting/package-lock.json
demo/meeting/package.json
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
2.3.0 Minor release
**Testing**
1. Have you successfully run `npm run build:release` locally? y
2. How did you test these changes? regression and unit tests

Publish amazon-chime-sdk-component-library-react@2.3.0

---

src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
src/providers/MeetingProvider/docs/MeetingProvider.stories.mdx
src/providers/MeetingProvider/index.tsx

**Issue #:** 
#492 
- Update documentation on re-usable meeting manager with respect to findings in above tagged issues [this](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/492#issuecomment-846317339) comment.
- We have scattered documentation for this, hence updated at all places.
**Testing**
Yes.
2. How did you test these changes? By running the storybook locally.

Update documentation on re-usable meeting manager

---

CHANGELOG.md
demo/chat/package-lock.json
demo/meeting/package-lock.json
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@2.5.0

---

src/hooks/sdk/docs/useMediaStreamMetrics.stories.mdx

**Issue #:** 
Fix typo in useMediaStreamMetrics storybook
**Testing**
2. How did you test these changes?  generate local storybook

Fix typo in useMediaStreamMetrics storybook

---

scripts/release.js

**Issue #:** 
Update broken release script. Chat demo no longer exists in this repo and some parts of the release script were erroring out
**Testing**
2. How did you test these changes? ran the script locally
3. If you made changes to the component library, have you provided corresponding documentation changes? no

Update release script

---

demo/meeting/serverless/template.yaml

Update Node lambda version to 14 in serverless demo.
**Testing**
2. How did you test these changes? Verified the meeting demo worked.

[Demo] Update Lambda Node version to 14 for serverless demo

---

CHANGELOG.md
demo/meeting/package-lock.json
demo/meeting/package.json
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@2.6.0

---

demo/meeting/src/containers/DevicePermissionControl/DevicePermissionControl.tsx
demo/meeting/src/containers/DynamicMeetingControls/index.tsx
src/components/howTos.stories.mdx

**Issue:** 
Improve storybook.
Add how-to instruction for view-only mode in storybook.
Format code based on JSLint.
**Testing**
Yes.
Run the meeting demo and check the change related components works well.
3. If you made changes to the component library, have you provided corresponding documentation changes? 
N/A

Add how-to for view-only mode and format the code

---

src/components/howTos.stories.mdx

**Issue #:** 
Add useMediaStreamMetrics documentation in How-tos
**Testing**
N/A
3. If you made changes to the component library, have you provided corresponding documentation changes? 
N/A

Add useMediaStreamMetrics documentation in How-tos

---

CHANGELOG.md
src/components/howTos.stories.mdx

**Issue #:** 
Update documentation for useMediaStreamMetrics in how-to doc
**Testing**

Update documentation for useMediaStreamMetrics in how-to

---

CHANGELOG.md
demo/meeting/package-lock.json
demo/meeting/package.json
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
Publish amazon-chime-sdk-component-library-react@2.7.0. Build the test url using npm 7.
**Testing**

Publish amazon-chime-sdk-component-library-react@2.7.0

---

README.md

**Issue #:** 
None
Update ReadMe.md to include Project Board
**Testing**
2. How did you test these changes? Yes

Update ReadMe.md to include Project Board

---

src/components/quickStarts.stories.mdx

**Issue #:** 
The storybook can not be deployed due to a unused import.
Remove the unused import in storybook.
**Testing**
Yes
Check that the storybook runs well.
N/A

Remove the unused import in storybook

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
- Publish amazon-chime-sdk-component-library-react@2.8.0
**Testing**
2. How did you test these changes? Ran `npm run release`, deploy the serverless meeting, and perform a sanity check

Publish amazon-chime-sdk-component-library-react@2.8.0

---

src/components/sdk/MeetingControls/AudioInputVFControl.tsx

**Issue #:** N/A
* Set `meetingManager.selectedAudioInputDevice` as the default value of `device` in `AudioInputVFControl`. So the default device won't be `none` when user joins the meeting.
* Add `devices.length` as dependency of `useEffect()`, so the dropdown list of microphone would be updated when the devices change.
**Testing**
2. How did you test these changes? 1) User joins the meeting by entering pin and name 2) User enter the meeting, the `Default` option is selected in Mic drop down in the meeting controls instead of `None` 3) User connects audio device in the middle of the meeting 4) Audio devices are updated properly in the meeting
3. If you made changes to the component library, have …

Update AudioInputVFControl component to fix Voice Focus related issue

---

package-lock.json

This reverts commit 271c0770d0b20529c96f2ad28149daa5efe9cdbe that is accidentally committed.

Revert "Update transitive deps (#597)"

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
* Publish amazon-chime-sdk-component-library-react@2.9.0
**Testing**
2. How did you test these changes? Ran `npm run release`, deploy the server-less meeting, and perform a sanity check

Publish amazon-chime-sdk-component-library-react@2.9.0

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

**Issue #:** 
Hot fix
Publish amazon-chime-sdk-component-library-react@2.9.1
**Testing**
2. How did you test these changes? run release script

Publish amazon-chime-sdk-component-library-react@2.9.1

---

README.md

**Issue #:** N/A
Since we enable Amazon Voice Focus feature, need to add notice in the ReadMe like we did in the [ReadMe](https://github.com/aws/amazon-chime-sdk-js#notice) of JS SDK.
**Testing**

Update readme to add Amazon Voice Focus notice

---

CHANGELOG.md
src/providers/DevicesProvider/docs/AudioInputProvider.stories.mdx

**Issue #:** [#624](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/624)
Add some documentation to mitigate this issue.
**Testing**

Add more documentation for AudioInputProvider

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@2.10.0

---

CHANGELOG.md
src/providers/DevicesProvider/AudioInputProvider.tsx

**Issue #:** [#636](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/636) 
Revert the commit: Add Amazon Voice Focus to default device to fix the breaking issue #636 
**Testing**
2. How did you test these changes? Run `npm run build:release`

Revert the change:Add Amazon Voice Focus to default device

---

CHANGELOG.md
src/components/quickStarts.stories.mdx
src/components/sdk/MeetingControls/VideoInputBackgroundBlurControl.tsx
src/components/sdk/MeetingControls/docs/VideoInputBackgroundBlurControl.stories.mdx
src/providers/BackgroundBlurProvider/docs/BackgroundBlurProvider.stories.mdx

**Issue #:** 
Add a short quickstart guide on background blur provider for visibility.
**Testing**
yes
n/a
n/a

Add Background Blur quickstart guide and update BG Blur Provider documentation

---

CHANGELOG.md
src/components/sdk/DeviceSelection/CameraSelection/BackgroundBlurCheckbox.tsx
src/components/sdk/DeviceSelection/docs/VideoFilterSelection.stories.mdx
src/components/sdk/DeviceSelection/index.tsx
src/index.ts

**Issue #:** 
Update the name of the file and export/imports.
**Testing**
2. yes
3. run the demo quickly

Update VideoFilterSelection to BackgroundBlurCheckbox

---

CHANGELOG.md
src/components/introduction.stories.mdx
src/components/quickStarts.stories.mdx

**Issue #:** 
N/A
* Fix missing newline or duplicate newline in CHANGELOG
* Add quick starts guide for data message with code example (tested) of remote mute/unmute all other attendees.
* Move the optional steps in Introduction section to Quick Starts section. 
* Delete the Meeting Join section in Quick Starts section.
* Capitalize the section titles in Quick Starts section to make them consistent.
Introduction section will focus on basic feature and Quick Starts will focus on advanced features.
**Testing**
Yes
Run storybooks locally and make sure it works well. …

Add doc for data message and improve the storybook

---

src/components/introduction.stories.mdx

**Issue #:** 
[Doc] Add link to Quick Starts section in Introduction section
**Testing**
Yes.
Run storybook locally and make sure it works well.
N/A

Add link to Quick Starts in Introduction

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@2.12.0

---

integration/app/test-demo/src/components/MeetingStatusDisplay.tsx
integration/app/test-demo/src/pages/Home.tsx
integration/app/test-demo/src/pages/RosterTestApp.tsx
integration/app/test-demo/webpack.config.js

**Issue #:** 
* Add `MeetingStatusDisplay` component to help check the meeting join and meeting leave.
* Update Webpack to only add proxy to Chime API request.
* Remove `bypass`
* Add `historyApiFallback`
* Change the `data-testid` of `<code>` from `attendeeId` based to `attendeeName` based.
**Testing**
N/A
Run the demo and confirm it works.
N/A

Improved roster test App to facilitate testing

---

package-lock.json
package.json

**Issue #:** 
The deploy action failed when the commit [upgrade some dependencies](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/688/files) merged to the master branch. 
Failed Github action: [Deploy Components Demo App Workflow #184](https://github.com/aws/amazon-chime-sdk-component-library-react/runs/4376479285?check_suite_focus=true)
Downgrade `@storybook/addon-knobs` to the previous version
**Testing**
2. How did you test these changes? Run `npm run deploy-storybook -- --ci` on local.
3. If you made changes to the component library, have you provided corresponding documentation changes? No, just dependency issue
By submitting this pull request, I confirm that my …

downgrade @storybook/addon-knobs

---

.storybook/main.tsx
package-lock.json
package.json

**Issue #:** 
1. Upgrade `@storybook/addon-knobs` from 6.29 to 6.40
2. Update the usage of below packages.
* `@storybook/addon-knobs`
* `@storybook/addon-storysource`
* `@storybook/addon-viewport`
3. Run `npm audit fix` to fix 3 vulnerable issues.
* `json-schema`
* `tmpl`
* `prismjs`
**Testing**
Yes
Test the change in the forked branch, this change can address 3 security alarm.
Test the story book with `npm run start` and `npm run build-storybook` locally, and confirm the storybook works well.
N/A
By submitting this pull request, I confirm that my contribution is …

Upgrade dependencies to fix some vulnerable issues

---

.github/workflows/deploy.yml

Update storybook deployer for the github access token credentials.
**Testing**
2. How did you test these changes? Change the action to run on pull request and verify that storybook is deployed successfully. https://github.com/aws/amazon-chime-sdk-component-library-react/actions/runs/1585389427

Update storybook deployer

---

.base-branch
.github/ISSUE_TEMPLATE/bug-report.yaml
.github/workflows/continuous-integration.yml
.github/workflows/deploy.yml
.github/workflows/publish.yml
.github/workflows/roster-integration.yml
CONTRIBUTING.md
scripts/release.js
src/components/quickStarts.stories.mdx

Rename our default branch from master to main.
**Testing**

Update master reference to main

---

CONTRIBUTING.md

Update CONTRIBUTING to on how to migrate to `main` branch
**Testing**

Update CONTRIBUTING to mention migration to main branch

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@2.13.0

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@2.14.0

---

README.md

**Issue #:** 
Add legal notices for background blur and replacement in the README.md.
**Testing**
=============================== Coverage summary ===============================
Statements   : 89.73% ( 2027/2259 )
Branches     : 64.7% ( 757/1170 )
Functions    : 78.34% ( 492/628 )
Lines        : 91.64% ( 1754/1914 )
================================================================================
Test Suites: 53 passed, 53 total
Tests:       231 passed, 231 total
no code change
no code change
By submitting this pull request, I confirm that my contribution is made …

Update README.md with background blur and replacement notices

---

src/components/quickStarts.stories.mdx

**Issue #:** 
Update `Enable Background Blur and Replacement` section in the quick start stories.
**Testing**
=============================== Coverage summary ===============================
Statements   : 89.73% ( 2027/2259 )
Branches     : 64.7% ( 757/1170 )
Functions    : 78.34% ( 492/628 )
Lines        : 91.64% ( 1754/1914 )
================================================================================
Test Suites: 53 passed, 53 total
Tests:       231 passed, 231 total
No code change.
No code change.
By submitting this pull request, I confirm that my …

Update background blur and replacement in quick starts docs

---

CHANGELOG.md
src/components/sdk/MeetingControls/AudioInputVFControl.tsx
src/providers/VoiceFocusProvider/index.tsx
src/types/index.ts

**Issue #:** 
Add Amazon Chime Echo Reduction for React SDK
**Testing**
Testing steps:
- Enable Web Audio. Enable Echo Reduction. Join the meeting
- Select one input audio device, and then click on "Enable voice focus". 
- Expect: ns_es model get download and exactly once.
- demo PR: https://github.com/aws-samples/amazon-chime-sdk/pull/128
Echo Reduction On:
Echo Reduction Off:
Default Voice Focus On:

Echo Reduction

---

src/providers/LocalVideoProvider/index.tsx
src/types/index.ts

**Issue #:** 
Export the hasReachedVideoLimit state
**Testing**
Yes
Just export the state
N/A

Export the hasReachedVideoLimit state

---

CHANGELOG.md
package-lock.json
package.json
src/versioning/Versioning.ts

Publish amazon-chime-sdk-component-library-react@2.15.0

---

package-lock.json
package.json
tst/hooks/sdk/useActiveSpeakersState.test.tsx

- Add `@testing-library/react-hooks` dev dependency to support testing hooks.
- Add a sample unit test for `useActiveSpeakersState`.
**Testing**
2. How did you test these changes? Manually run the test.

Add unit test for useActiveSpeakersState

---

CHANGELOG.md
package-lock.json
package.json

Bump the version to the next beta version
**Testing**

Version bump for amazon-chime-sdk-component-library-react@3.0.0-beta.0

---

.github/workflows/deploy.yml
CHANGELOG.md
integration/app/test-demo/package-lock.json
integration/app/test-demo/package.json
package-lock.json
package.json
src/components/migrationToV3.stories.mdx
src/components/quickStarts.stories.mdx
src/components/sdk/MeetingControls/AudioOutputControl.tsx
src/components/sdk/RosterAttendee/index.tsx
src/components/ui/Checkbox/index.tsx
src/components/ui/Input/InputWrapper.tsx
src/components/ui/Input/Styled.tsx
src/components/ui/Modal/ModalButtonGroup.tsx
src/components/ui/Select/Styled.tsx
src/providers/BackgroundReplacementProvider/index.tsx
src/providers/MeetingProvider/MeetingManager.ts
src/providers/MeetingProvider/docs/MeetingManager.stories.mdx
src/providers/MeetingProvider/types.ts
src/providers/introduction.stories.mdx
tst/hooks/sdk/useActiveSpeakersState.test.tsx
tst/providers/MeetingProvider/index.test.tsx

**Issue #724:** 
Need to update component library for V3 changes
- Updated to v3 beta.0
- Removed deprecated functionality 
- Updated Eventcontroler to v3
**Testing**
Yes
- Launched meeting demo with these changes
- Created a meeting
- Looked for events in the console logger from Eventcontroller publish event
Yes

[V3] Update event controller to adopt to JS SDK V3 changes

---

CHANGELOG.md
package-lock.json
package.json
scripts/version-utils.js

- Bump the next dev version.
- Remove a debug console.log in release script
**Testing**

Version bump for amazon-chime-sdk-component-library-react@3.0.0-beta.1

---

scripts/release.js

Minor fix for release script to pack the library before deploying testing demo.
**Testing**
2. 
3. How did you test these changes? Manually run redeploy demo step in release script
4. If you made changes to the component library, have you provided corresponding documentation changes? No

Build and pack library code when deploying demo

---

scripts/check-codestyle.js

**Issue #:** 
`npm run check` which check codestyles will flag the auto-generated file `version.ts` for copyright violation.
Add a function to skip git ignore file when running copyright check. This is the same function in JS SDK.
**Testing**
2. How did you test these changes? Manually run `npm run check`

Ignore version.ts when checking code style

---

CHANGELOG.md
README.md
src/components/migrationToV3.stories.mdx

**Issue #:** 
* Update CHANGELOG to summarize v3 changes.
* Add link to migration guide in CHANGELOG and README.
**Testing**
Yes
N/A, doc changes only.
N/A, doc changes only.

Update CHANGELOG to summarize v3 changes

---

README.md
src/components/sdk/MeetingControls/docs/AudioInputVFControl.stories.mdx
src/providers/VoiceFocusProvider/docs/VoiceFocusProvider.stories.mdx
src/providers/VoiceFocusProvider/docs/useVoiceFocus.stories.mdx

**Issue #:** 
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/784
Documentation needs to be updated for Echo Reduction since CreatingMeetingResponse is needed in spec of VoiceFocusProvider to get initialized and download models. 
**Testing**
yes
`npm start` and see changes in Storybook
yes

Echo Reduction documentation updates

---

CHANGELOG.md
package-lock.json
package.json

Version bump for amazon-chime-sdk-component-library-react@3.4.0

---

CHANGELOG.md
package-lock.json
package.json

Version bump for amazon-chime-sdk-component-library-react@3.5.0

---

CHANGELOG.md
package-lock.json
package.json

Version bump for amazon-chime-sdk-component-library-react@3.6.0

---

CHANGELOG.md
package-lock.json
package.json

Version bump for amazon-chime-sdk-component-library-react@3.7.0

---

CHANGELOG.md
package-lock.json
package.json

Version bump for amazon-chime-sdk-component-library-react@3.8.0

---

package-lock.json
package.json

**Issue #:** 
Update JS SDK version to 3.18.x
**Testing**
yes
Used in the meeting demo successfully.
5. If you made changes to the component library, have you provided corresponding documentation changes?

Update JS SDK version

---

CHANGELOG.md

**Issue #:** 
No change log for 3.8.0 release.
Add change log for node 20 support
**Testing**
Yes
N/A
Yes

Add CHANGELOG for node 20 support

---

CHANGELOG.md
package-lock.json
package.json

**Issue #:** 
NA
version bump for development branch (main)
**Testing**
yes
release script
NA

Version bump for amazon-chime-sdk-component-library-react@3.9.0

---

integration/app/test-demo/package-lock.json
integration/app/test-demo/package.json

**Issue #:** 
- Bump react dependencies to fix errors in integration test demo.
**Testing**
Yes
Ran test demo and verified the functionality.
No, just demo changes

Bump dependencies version to fix type error in integration test demo

---

CHANGELOG.md
src/providers/BackgroundReplacementProvider/index.tsx

**Issue #:** 
Change changeBackgroundReplacementImage return type to Promise
**Testing**
Yes
Test with changes in demo.
Will provide in a follow-up PR.

Change changeBackgroundReplacementImage return type to Promise

---

CHANGELOG.md
package-lock.json
package.json

Version bump for amazon-chime-sdk-component-library-react@3.10.0

---

src/providers/MeetingProvider/docs/MeetingManager.mdx

**Issue #:**  None
This config no longer has any effect.
**Testing**
no
I didn't
n/a

Remove deprecated configuration from priority policy usage

---

integration/app/test-demo/package-lock.json
integration/package-lock.json
integration/package.json

**Issue #:** 
Security patching
- Patch vulnerabilities in integration/ and upgrade drivers for chrome and firefox
**Testing**
Yes
Run integration test and verify it passes
4. If you made changes to the component library, have you provided corresponding documentation changes?
N/A

Patch vulnerabilities in integration/ and upgrade drivers for chrome and firefox

---

package-lock.json

**Issue #:** 
Security patching in package-lock.json in root.
Patch vulnerabilities in root dir
**Testing**
Yes
Install React SDK in meeting demo and tested e2e to verify audio, video, VF, background blur/filter, media metrics.
N/A

Patch vulnerabilities in root dir

---

.github/workflows/deploy.yml
.github/workflows/roster-integration.yml

Replace IAM creds with role

---

CHANGELOG.md
package-lock.json
package.json
scripts/release.js

Version bump for amazon-chime-sdk-component-library-react@3.11.0

---

.github/workflows/deploy.yml
package-lock.json

**Issue #:** 
The job needs to run within an environment in order to deploy the storybook to that environment. 
**Testing**
Yes
Has to be tested by pushing, you cannot deploy on the pull-request trigger.

Run deploy script inside github page environment

---

src/providers/ContentShareProvider/docs/ContentShareProvider.mdx

**Issue #:** 
Update doc for canStartContentShare
**Testing**
yes
N/A
Yes

Update doc for canStartContentShare

---

CHANGELOG.md
src/components/sdk/MeetingControls/docs/AudioInputVFControl.mdx
src/providers/MeetingProvider/docs/MeetingManager.mdx
src/providers/VoiceFocusProvider/docs/VoiceFocusProvider.mdx

**Issue #:** 
- Add documentation for Voice Focus and Web Audio best practice
**Testing**
Yes
Verified documentation in local storybook.
Yes

Add documentation for Voice Focus and Web Audio best practice
